### ISSUE TITLE
Add MySQL method for MySQL Backend

### ISSUE THREAD

**Issue by blairj09** [tidyverse/dbplyr#256] opened 2019-03-05 18:50 UTC
Currently, the MySQL backend supports `MySQLConnection` and `MariaDBConnection`. ODBC connections made to MySQL have class `MySQL`, which should also be supported.

CC: @edgararuiz

**Comment by hadley** [comment] 2019-03-12 18:07
Oh this is a duplicate of #238

**Closed by hadley** 2019-03-12 18:07 UTC
Labels: feature, verb trans :robot:
