### ISSUE TITLE
mutate_at fails to identify columns specified by .vars parameter

### ISSUE THREAD

**Issue by bradenkinard** [tidyverse/dbplyr#305] opened 2019-05-20 18:27 UTC
Some code we have as part of a function in an internal R package started failing tests that previously worked as of a few weeks ago (the last time I ran our unit tests). I narrowed the issue down to mutate_at failing to identify variables specified in the .vars argument. 

Here is a toy example with the same behavior. Here I am simply trying to replace NA values in the specified columns with 0:

``` r
library(dplyr)
library(dbplyr)

mf <- memdb_frame(A = c(NA, 1, NA, 2, 2), 
                  B = c(1, 2, 3, NA, NA),
                  C = c(NA, NA, 3, 2, 1),
                  D = c(NA, 4, NA, 2, 1))

replace_func <- function(val, replace) {
  ifelse(is.na(val), replace, val)
}

mf %>% 
  mutate_at(c("A", "B"), replace_func, replace = 0)
#> Error in ifelse(is.na(val), replace, val): object 'A' not found
```

<sup>Created on 2019-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

<details>

I wanted to confirm that it wasn't a dumb mistake in my code causing the error, so I also ran an example taken directly from the mutate_at reference documentation (albeit converted to scenario involving a database) which also fails the same way:

``` r
library(dplyr)
library(dbplyr)


starwars_mf <- starwars %>% 
  select(name:mass) %>% 
  tbl_memdb()

scale2 <- function(x, na.rm = FALSE) (x - mean(x, na.rm = na.rm)) / sd(x, na.rm)

starwars_mf %>% 
  mutate_at(c("height", "mass"), scale2, na.rm = TRUE)
#> Error in (function (x, na.rm = FALSE) : object 'height' not found

starwars_mf %>% 
  mutate_at(c("height", "mass"), ~scale2(., na.rm = TRUE))
#> Error in as.pairlist(list(...)): object 'height' not found
```

<sup>Created on 2019-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
 
Note that both examples do work in a regular dplyr context on local data frames:

``` r
library(dplyr)
library(dbplyr)

mf <- tibble(A = c(NA, 1, NA, 2, 2), 
             B = c(1, 2, 3, NA, NA),
             C = c(NA, NA, 3, 2, 1),
             D = c(NA, 4, NA, 2, 1))

replace_func <- function(val, replace) {
  ifelse(is.na(val), replace, val)
}

mf %>% 
  mutate_at(c("A", "B"), replace_func, replace = 0)
#> # A tibble: 5 x 4
#>       A     B     C     D
#>   <dbl> <dbl> <dbl> <dbl>
#> 1     0     1    NA    NA
#> 2     1     2    NA     4
#> 3     0     3     3    NA
#> 4     2     0     2     2
#> 5     2     0     1     1
```

<sup>Created on 2019-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

My session info:

```
R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dbplyr_1.4.0 dplyr_0.8.1 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1       crayon_1.3.4     assertthat_0.2.1 R6_2.4.0         DBI_1.0.0        magrittr_1.5     pillar_1.3.1     rlang_0.3.4     
 [9] rstudioapi_0.10  tools_3.5.3      glue_1.3.1       purrr_0.3.2      yaml_2.2.0       compiler_3.5.3   pkgconfig_2.0.2  tidyselect_0.2.5
[17] tibble_2.1.1  
```

</details>

**Comment by vitallish** [comment] 2019-05-24 16:40
I see the same issue with `summarise_at`. While I wasn't able to figure out the precise cause of the issue - I believe it has to do with the recent dplyr upgrade to 0.8.1. I rolled my system dplyr back to 0.8.0.1 which fixed the issue.

**Comment by hadley** [comment] 2019-05-30 22:22
Are you sure this ever worked? I can't imagine that `replace_func()` was ever successfully translated to SQL, because the translation has never worked for user defined functions.

**Comment by hadley** [comment] 2019-05-30 22:25
This seems to work fine with functions with known translation, so I'm going to close this issue:

``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)

lf <- lazy_frame(
  A = c(NA, 1, NA, 2, 2), 
  B = c(1, 2, 3, NA, NA),
  C = c(NA, NA, 3, 2, 1),
  D = c(NA, 4, NA, 2, 1)
)

lf %>% mutate_all(~ rank(.))
#> <SQL>
#> SELECT RANK() OVER (ORDER BY `A`) AS `A`, RANK() OVER (ORDER BY `B`) AS `B`, RANK() OVER (ORDER BY `C`) AS `C`, RANK() OVER (ORDER BY `D`) AS `D`
#> FROM `df`
```

<sup>Created on 2019-05-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by bradenkinard** [comment] 2019-05-30 23:02
> Are you sure this ever worked? I can't imagine that `replace_func()` was ever successfully translated to SQL, because the translation has never worked for user defined functions.

Well technically in the actual code in which I first encountered the bug, I didn't explicitly define ```replace_func()``` prior to the call. Instead it looked like this:

``` r
mf %>% 
  mutate_at(c("A", "B"), list(~ifelse(is.na(.), 0, .)))
```

At some point in my testing I switched over to using ```replace_func()``` and just assumed it was functionally equivalent to the original example. Apologies if there are meaningful differences between the two that are confusing the underlying issue. But I can confirm that it works on older versions of dbplyr and dplyr:

``` r
library(dplyr)
library(dbplyr)

mf <- memdb_frame(A = c(NA, 1, NA, 2, 2), 
                  B = c(1, 2, 3, NA, NA),
                  C = c(NA, NA, 3, 2, 1),
                  D = c(NA, 4, NA, 2, 1))

mf %>% 
  mutate_at(c("A", "B"), list(~ifelse(is.na(.), 0, .)))
#> # Source:   lazy query [?? x 4]
#> # Database: sqlite 3.22.0 [:memory:]
#>       A     B     C     D
#>   <dbl> <dbl> <dbl> <dbl>
#> 1     0     1    NA    NA
#> 2     1     2    NA     4
#> 3     0     3     3    NA
#> 4     2     0     2     2
#> 5     2     0     1     1
```

<sup>Created on 2019-05-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Session info:
``` r
sessionInfo()
#> R version 3.5.1 (2018-07-02)
#> Platform: x86_64-apple-darwin15.6.0 (64-bit)
#> Running under: macOS  10.14.2
#> 
#> Matrix products: default
#> BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_3.5.1  magrittr_1.5    tools_3.5.1     htmltools_0.3.6
#>  [5] yaml_2.2.0      Rcpp_1.0.0      stringi_1.2.4   rmarkdown_1.12 
#>  [9] highr_0.7       knitr_1.22      stringr_1.3.1   xfun_0.6       
#> [13] digest_0.6.18   evaluate_0.13
```

<sup>Created on 2019-05-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

But when using dbplyr_1.4.0 and dplyr_0.8.1 the above code will throw the error in my original post.

**Comment by hadley** [comment] 2019-05-31 14:37
This is why creating a reproducible example is SO important. In the future please don't include session info unless it's asked for, and work to generate a reprex that shows the problem.

``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)

lf <- lazy_frame(
  A = c(NA, 1, NA, 2, 2), 
  B = c(1, 2, 3, NA, NA),
  C = c(NA, NA, 3, 2, 1),
  D = c(NA, 4, NA, 2, 1)
)

# works
lf %>% mutate(A = ifelse(is.na(A), 0, A))
#> <SQL>
#> SELECT CASE WHEN (((`A`) IS NULL)) THEN (0.0) WHEN NOT(((`A`) IS NULL)) THEN (`A`) END AS `A`, `B`, `C`, `D`
#> FROM `df`

# fails
lf %>% mutate_all(~ifelse(is.na(.), 0, .))
#> <SQL>
#> Error in sql_if(test, yes, no): argument "yes" is missing, with no default
```

<sup>Created on 2019-05-31 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by hadley** [comment] 2019-05-31 14:38
(NB: for this specific case you can more concisely describe the operation as a `coalesce()`)

**Comment by hadley** [comment] 2019-06-04 20:29
Turns out that this is a duplicate of #306

**Closed by hadley** 2019-06-04 20:29 UTC
Labels: bug, verb trans :robot:
