### ISSUE TITLE
missing right parenthesis oracle

### ISSUE THREAD

**Issue by fahadshery** [tidyverse/dbplyr#359] opened 2019-09-18 12:32 UTC
Already seen [here](https://github.com/tidyverse/dplyr/issues/2928) but my issue remains hence re-opening the issue again.

This works:
```r
show_query(tbl(con, in_schema('"my_schema"', "my_table")))
<SQL>
SELECT *
FROM "my_schema".my_table
```

This doesn't work
```r
show_query(tbl(con, "my_table"))
Error: <SQL> 'SELECT *
FROM ("my_table") "zzz24"
WHERE (0 = 1)'
  nanodbc/nanodbc.cpp:1587: 42S02: [Oracle][ODBC][Ora]ORA-00942: table or view does not exist
```

This works too:

```r
DBI::dbGetQuery(con, "select *
                  from my_table 
                  fetch FIRST 6 ROWS ONLY") 

OR
DBI::dbGetQuery(con, "SELECT *
FROM \"my_schema\".my_table
WHERE ROWNUM < 5 ")
```

Now what I am trying to do is to overcome `oracle`'s 1000 limit in the `IN` clause.

I generated random numbers by:

```{r}
sample_rn <-  sample(1:5423586,size = 10000)
sample_rn[1:10]
```

then created row_numbers by:

```r
my_table %>% group_by(MY_GROUP) %>% 
  arrange(REPORT_DATE) %>% 
  mutate(rn = row_number()) %>% 
  filter( rn %in% !!sample_rn)%>% show_query()
```

Then take this query... clean a little bit and run in `SQL developer` to make sure it `works`.

Now when I get this query back to `DBI::dbGetQuery(con,"sql long query") 
It gives error that `right parenthsis missing`.

Not sure if this is a query `parsing` issue?

**Comment by hadley** [comment] 2019-12-13 19:44
Can you please provide a minimal reproducible example using the [reprex](http://reprex.tidyverse.org) package? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it. If you've never made a minimal reprex before, there is lots of good advice [here](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html).

**Comment by abesolberg** [comment] 2020-02-13 13:56
I had a similar issue using the jdbcDriver. Did you add these lines to your code as per the databases using R [page](https://db.rstudio.com/databases/oracle/)? 

`sql_translate_env.JDBCConnection <- dbplyr:::sql_translate_env.Oracle`
`sql_select.JDBCConnection <- dbplyr:::sql_select.Oracle`
`sql_subquery.JDBCConnection <- dbplyr:::sql_subquery.Oracle`

**Comment by hadley** [comment] 2020-04-14 22:04
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2020-04-14 22:04 UTC
Labels: reprex
