### ISSUE TITLE
Ambiguous column names in right-join in MS SQL Server 

### ISSUE THREAD

**Issue by awong234** [tidyverse/dbplyr#553] opened 2020-12-01 14:48 UTC
The update to v2 lessened the requirements to disambiguate column names to increase readability of the generated SQL. I believe that this has introduced some bugs in right-joins on MS SQL Server. What follows isn't a full reprex because of the SQL Server dependency, but so long as one is available and the proper connection established then this should illustrate the issue.

```
library(dplyr)
library(odbc)
library(dbplyr)

# Establish a proper connection to SQL Server.
# con = dbConnect()

mtcars_t = as_tibble(mtcars, rownames = 'carname')
mtcars_t2 = rename(mtcars_t, CARNAME = carname, CYL = cyl)

dbWriteTable(con, DBI::SQL("dbo.A131485_test"), mtcars_t, overwrite = TRUE)

tbl(con, in_schema('dbo', 'A131485_test')) %>% 
    right_join(mtcars_t2, by = c('carname' = 'CARNAME', 'cyl' = 'CYL'), copy = TRUE)
```

What results is the following error under version 2

```
Error: nanodbc/nanodbc.cpp:1655: 42000: [Microsoft][SQL Server Native Client 11.0][SQL Server]Ambiguous column name 'CARNAME'.  [Microsoft][SQL Server Native Client 11.0][SQL Server]Ambiguous column name 'CYL'.  [Microsoft][SQL Server Native Client 11.0][SQL Server]Statement(s) could not be prepared. 
<SQL> 'SELECT TOP 56 *
FROM (SELECT "CARNAME" AS "carname", "LHS"."mpg" AS "mpg.x", "CYL" AS "cyl", "LHS"."disp" AS "disp.x", "LHS"."hp" AS "hp.x", "LHS"."drat" AS "drat.x", "LHS"."wt" AS "wt.x", "LHS"."qsec" AS "qsec.x", "LHS"."vs" AS "vs.x", "LHS"."am" AS "am.x", "LHS"."gear" AS "gear.x", "LHS"."carb" AS "carb.x", "RHS"."mpg" AS "mpg.y", "RHS"."disp" AS "disp.y", "RHS"."hp" AS "hp.y", "RHS"."drat" AS "drat.y", "RHS"."wt" AS "wt.y", "RHS"."qsec" AS "qsec.y", "RHS"."vs" AS "vs.y", "RHS"."am" AS "am.y", "RHS"."gear" AS "gear.y", "RHS"."carb" AS "carb.y"
FROM "dbo"."A131485_test" AS "LHS"
RIGHT JOIN "#dbplyr_001" AS "RHS"
ON ("LHS"."carname" = "RHS"."CARNAME" AND "LHS"."cyl" = "RHS"."CYL")
```

<details>
Whereas under version 1.4.4 the operation succeeds as expected:

```
Created a temporary table named: #dbplyr_001
# Source:   lazy query [?? x 22]
# Database: Microsoft SQL Server 13.00.5426[PROG1\A131485@SCBISS25/BISSClaimsCntrlStage]
   carname mpg.x   cyl disp.x  hp.x drat.x  wt.x qsec.x  vs.x  am.x gear.x carb.x mpg.y disp.y  hp.y drat.y
   <chr>   <dbl> <dbl>  <dbl> <dbl>  <dbl> <dbl>  <dbl> <dbl> <dbl>  <dbl>  <dbl> <dbl>  <dbl> <dbl>  <dbl>
 1 Mazda ~  21       6  160     110   3.9   2.62   16.5     0     1      4      4  21    160     110   3.9 
 2 Mazda ~  21       6  160     110   3.9   2.88   17.0     0     1      4      4  21    160     110   3.9 
 3 Datsun~  22.8     4  108      93   3.85  2.32   18.6     1     1      4      1  22.8  108      93   3.85
 4 Hornet~  21.4     6  258     110   3.08  3.22   19.4     1     0      3      1  21.4  258     110   3.08
 5 Hornet~  18.7     8  360     175   3.15  3.44   17.0     0     0      3      2  18.7  360     175   3.15
 6 Valiant  18.1     6  225     105   2.76  3.46   20.2     1     0      3      1  18.1  225     105   2.76
 7 Duster~  14.3     8  360     245   3.21  3.57   15.8     0     0      3      4  14.3  360     245   3.21
 8 Merc 2~  24.4     4  147.     62   3.69  3.19   20       1     0      4      2  24.4  147.     62   3.69
 9 Merc 2~  22.8     4  141.     95   3.92  3.15   22.9     1     0      4      2  22.8  141.     95   3.92
10 Merc 2~  19.2     6  168.    123   3.92  3.44   18.3     1     0      4      4  19.2  168.    123   3.92
11 Merc 2~  17.8     6  168.    123   3.92  3.44   18.9     1     0      4      4  17.8  168.    123   3.92
12 Merc 4~  16.4     8  276.    180   3.07  4.07   17.4     0     0      3      3  16.4  276.    180   3.07
13 Merc 4~  17.3     8  276.    180   3.07  3.73   17.6     0     0      3      3  17.3  276.    180   3.07
14 Merc 4~  15.2     8  276.    180   3.07  3.78   18       0     0      3      3  15.2  276.    180   3.07
15 Cadill~  10.4     8  472     205   2.93  5.25   18.0     0     0      3      4  10.4  472     205   2.93
16 Lincol~  10.4     8  460     215   3     5.42   17.8     0     0      3      4  10.4  460     215   3   
17 Chrysl~  14.7     8  440     230   3.23  5.34   17.4     0     0      3      4  14.7  440     230   3.23
18 Fiat 1~  32.4     4   78.7    66   4.08  2.2    19.5     1     1      4      1  32.4   78.7    66   4.08
19 Honda ~  30.4     4   75.7    52   4.93  1.62   18.5     1     1      4      2  30.4   75.7    52   4.93
20 Toyota~  33.9     4   71.1    65   4.22  1.84   19.9     1     1      4      1  33.9   71.1    65   4.22
21 Toyota~  21.5     4  120.     97   3.7   2.46   20.0     1     0      3      1  21.5  120.     97   3.7 
22 Dodge ~  15.5     8  318     150   2.76  3.52   16.9     0     0      3      2  15.5  318     150   2.76
23 AMC Ja~  15.2     8  304     150   3.15  3.44   17.3     0     0      3      2  15.2  304     150   3.15
24 Camaro~  13.3     8  350     245   3.73  3.84   15.4     0     0      3      4  13.3  350     245   3.73
25 Pontia~  19.2     8  400     175   3.08  3.84   17.0     0     0      3      2  19.2  400     175   3.08
26 Fiat X~  27.3     4   79      66   4.08  1.94   18.9     1     1      4      1  27.3   79      66   4.08
27 Porsch~  26       4  120.     91   4.43  2.14   16.7     0     1      5      2  26    120.     91   4.43
28 Lotus ~  30.4     4   95.1   113   3.77  1.51   16.9     1     1      5      2  30.4   95.1   113   3.77
29 Ford P~  15.8     8  351     264   4.22  3.17   14.5     0     1      5      4  15.8  351     264   4.22
30 Ferrar~  19.7     6  145     175   3.62  2.77   15.5     0     1      5      6  19.7  145     175   3.62
31 Masera~  15       8  301     335   3.54  3.57   14.6     0     1      5      8  15    301     335   3.54
32 Volvo ~  21.4     4  121     109   4.11  2.78   18.6     1     1      4      2  21.4  121     109   4.11
# ... with 6 more variables: wt.y <dbl>, qsec.y <dbl>, vs.y <dbl>, am.y <dbl>, gear.y <dbl>, carb.y <dbl>
```

The underlying query in version 1.4.4 is as follows, which succeeds because all column names use aliases by default.

```
Created a temporary table named: #dbplyr_003
<SQL>
SELECT "RHS"."CARNAME" AS "carname", "LHS"."mpg" AS "mpg.x", "RHS"."CYL" AS "cyl", "LHS"."disp" AS "disp.x", "LHS"."hp" AS "hp.x", "LHS"."drat" AS "drat.x", "LHS"."wt" AS "wt.x", "LHS"."qsec" AS "qsec.x", "LHS"."vs" AS "vs.x", "LHS"."am" AS "am.x", "LHS"."gear" AS "gear.x", "LHS"."carb" AS "carb.x", "RHS"."mpg" AS "mpg.y", "RHS"."disp" AS "disp.y", "RHS"."hp" AS "hp.y", "RHS"."drat" AS "drat.y", "RHS"."wt" AS "wt.y", "RHS"."qsec" AS "qsec.y", "RHS"."vs" AS "vs.y", "RHS"."am" AS "am.y", "RHS"."gear" AS "gear.y", "RHS"."carb" AS "carb.y"
FROM dbo.A131485_test AS "LHS"
RIGHT JOIN "#dbplyr_003" AS "RHS"
ON ("LHS"."carname" = "RHS"."CARNAME" AND "LHS"."cyl" = "RHS"."CYL")
```

I am using driver SQL Server Native Client 11.0. The rest of my package information is as follows, but `dbplyr` is at 2.0.0 for the first error, and 1.4.4 for the successful second example. 

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dbplyr_1.4.4 odbc_1.3.0   dplyr_1.0.2 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6     rstudioapi_0.11  xml2_1.3.2       magrittr_1.5     hms_0.5.3        tidyselect_1.1.0
 [7] bit_1.1-15.2     R6_2.4.1         rlang_0.4.8      fansi_0.4.1      stringr_1.4.0    blob_1.2.1      
[13] tools_3.6.1      packrat_0.5.0    cnxn_0.2.2       utf8_1.1.4       cli_2.0.2        DBI_1.1.0       
[19] ellipsis_0.3.1   yaml_2.2.1       bit64_0.9-7      assertthat_0.2.1 tibble_3.0.1     lifecycle_0.2.0 
[25] crayon_1.3.4     keyring_1.1.0    ini_0.3.1        purrr_0.3.4      vctrs_0.3.4      glue_1.4.2      
[31] stringi_1.4.6    compiler_3.6.1   pillar_1.4.4     generics_0.1.0   pkgconfig_2.0.3 
```
</details>

**Comment by awong234** [comment] 2020-12-01 14:51
The MS SQL Server environment is managed for us in a large company, but here are some specs in case it helps:

![image](https://user-images.githubusercontent.com/37594391/100755899-a9c31480-33ba-11eb-93a8-aa9e4cfe5b73.png)

Let me know if there is more information you require, thank you!

**Comment by hadley** [comment] 2021-01-21 14:14
Would you mind creating a reprex with a simpler data frame?

**Comment by hadley** [comment] 2021-01-21 15:40
Is this specifically about columns with different cases? I can't reproduce what I think is the same problem in postgres:

``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)

con <- DBI::dbConnect(RPostgres::Postgres(),
  dbname = "test",
  host = "localhost",
  user = ""
)

df1 <- copy_to(con, data.frame(x = 1, y = 2), "test1")
df2 <- copy_to(con, data.frame(X = 1, y = 2, x = 3), "test2")

df1 %>% left_join(df2, by = c("x" = "X"))
#> # Source:   lazy query [?? x 4]
#> # Database: postgres [hadley@localhost:5432/test]
#>     x.x   y.x   y.y   x.y
#>   <dbl> <dbl> <dbl> <dbl>
#> 1     1     2     2     3
df1 %>% left_join(df2, by = c("x" = "X")) %>% show_query()
#> <SQL>
#> SELECT "LHS"."x" AS "x.x", "LHS"."y" AS "y.x", "RHS"."y" AS "y.y", "RHS"."x" AS "x.y"
#> FROM "test1" AS "LHS"
#> LEFT JOIN "test2" AS "RHS"
#> ON ("LHS"."x" = "RHS"."X")
```

<sup>Created on 2021-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by hadley** [comment] 2021-01-21 15:42
Although I do see it in SQLite where column names are case-insensitive:

``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)

con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")

df1 <- copy_to(con, data.frame(x = 1, y = 2), "test1")
df2 <- copy_to(con, data.frame(X = 1, y = 2), "test2")

df1 %>% left_join(df2, by = c("x" = "X"))
#> Error: ambiguous column name: x
df1 %>% left_join(df2, by = c("x" = "X")) %>% show_query()
#> <SQL>
#> SELECT `x`, `LHS`.`y` AS `y.x`, `RHS`.`y` AS `y.y`
#> FROM `test1` AS `LHS`
#> LEFT JOIN `test2` AS `RHS`
#> ON (`LHS`.`x` = `RHS`.`X`)
```

<sup>Created on 2021-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

If it's simply to do with case-(in)sensitivity on the database side, I'm not sure that there's anything dbplyr can do about it.

**Comment by awong234** [comment] 2021-01-21 18:36
Hi @hadley , thanks for replying, and for the keynote today!

Yes the problem seems to be limited to mixed casing. However, the operation succeeds in version 1.4+, so I think it is related to how `dbplyr` formats the SQL query. Below, I run the same code in two renv environments, with identical packages except for `dbplyr`, where one has version 1.4.4, and the other has version 2.0.0. 

The lynchpin as far as I can observe is the `select` statement in each; with 1.4.4, we see ` SELECT "LHS"."x" AS "x", "LHS"."y" AS "y", "RHS"."z" AS "z"`, but with 2.0.0 we see `SELECT "x", "y", "z"`; the rest of the query is the same. I think this was noted in the release notes for 2.0.0 as a step to reduce complexity of the generated query, but I think it is causing issues (SQL Server and RSQLite used below).

> Joins now only use aliases where needed to disambiguate columns; this should
make generated queries more readable.

# `dbplyr` version 1.4.4

``` r
suppressWarnings({
    library(dplyr)
    library(odbc)
    library(dbplyr)
    library(RSQLite)
})
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'dbplyr'
#> The following objects are masked from 'package:dplyr':
#> 
#>     ident, sql

con = odbc::dbConnect(odbc::odbc(),
                      driver = "ODBC Driver 17 for SQL Server",
                      server = Sys.getenv("server"),
                      database = Sys.getenv("database"),
                      Trusted_Connection = "yes")

# Simpler table
x1 = tibble(x = 'a', y = 1)
x2 = tibble(X = 'a', z = 2)

dbWriteTable(con, "test", x1, overwrite = TRUE)

q = tbl(con, "test") %>%
    left_join(x2, by = c('x' = 'X'), copy = TRUE)
#> Created a temporary table named: #dbplyr_001
q
#> # Source:   lazy query [?? x 3]
#> # Database: Microsoft SQL Server
#> #   13.00.5426[PROG1\A131485@SCBISS25/BISSClaimsCntrlStage]
#>   x         y     z
#>   <chr> <dbl> <dbl>
#> 1 a         1     2
q %>% show_query()
#> <SQL>
#> SELECT "LHS"."x" AS "x", "LHS"."y" AS "y", "RHS"."z" AS "z"
#> FROM "test" AS "LHS"
#> LEFT JOIN "#dbplyr_001" AS "RHS"
#> ON ("LHS"."x" = "RHS"."X")

dbRemoveTable(con, 'test')

con = odbc::dbConnect(RSQLite::SQLite(), ":memory:")

x1 = tibble(x = 'a', y = 1)
x2 = tibble(X = 'a', z = 2)

dbWriteTable(con, "test", x1, overwrite = TRUE)

q = tbl(con, "test") %>%
    left_join(x2, by = c('x' = 'X'), copy = TRUE)
q
#> # Source:   lazy query [?? x 3]
#> # Database: sqlite 3.34.0 [:memory:]
#>   x         y     z
#>   <chr> <dbl> <dbl>
#> 1 a         1     2
q %>% show_query()
#> <SQL>
#> SELECT `LHS`.`x` AS `x`, `LHS`.`y` AS `y`, `RHS`.`z` AS `z`
#> FROM `test` AS `LHS`
#> LEFT JOIN `dbplyr_003` AS `RHS`
#> ON (`LHS`.`x` = `RHS`.`X`)

sessionInfo()
#> R version 3.6.1 (2019-07-05)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 18363)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices datasets  utils     methods   base     
#> 
#> other attached packages:
#> [1] RSQLite_2.2.2 dbplyr_1.4.4  odbc_1.3.0    dplyr_1.0.2  
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.6       knitr_1.30       magrittr_2.0.1   hms_1.0.0       
#>  [5] bit_4.0.4        tidyselect_1.1.0 R6_2.5.0         rlang_0.4.10    
#>  [9] fansi_0.4.1      blob_1.2.1       stringr_1.4.0    highr_0.8       
#> [13] tools_3.6.1      xfun_0.20        utf8_1.1.4       cli_2.2.0       
#> [17] DBI_1.1.1        htmltools_0.5.1  ellipsis_0.3.1   assertthat_0.2.1
#> [21] bit64_4.0.5      yaml_2.2.1       digest_0.6.27    tibble_3.0.4    
#> [25] lifecycle_0.2.0  crayon_1.3.4     purrr_0.3.4      vctrs_0.3.6     
#> [29] memoise_1.1.0    glue_1.4.2       evaluate_0.14    rmarkdown_2.6   
#> [33] stringi_1.5.3    compiler_3.6.1   pillar_1.4.7     generics_0.1.0  
#> [37] renv_0.11.0      pkgconfig_2.0.3
```

<sup>Created on 2021-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


# `dbplyr` version 2.0.0

``` r
suppressWarnings({
    library(dplyr)
    library(odbc)
    library(dbplyr)
    library(RSQLite)
})
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'dbplyr'
#> The following objects are masked from 'package:dplyr':
#> 
#>     ident, sql

con = odbc::dbConnect(odbc::odbc(),
                      driver = "ODBC Driver 17 for SQL Server",
                      server = Sys.getenv("server"),
                      database = Sys.getenv("database"),
                      Trusted_Connection = "yes")

# Simpler table
x1 = tibble(x = 'a', y = 1)
x2 = tibble(X = 'a', z = 2)

dbWriteTable(con, "test", x1, overwrite = TRUE)

q = tbl(con, "test") %>%
    left_join(x2, by = c('x' = 'X'), copy = TRUE)
#> Created a temporary table named #dbplyr_001
q
#> Error: nanodbc/nanodbc.cpp:1655: 42000: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Ambiguous column name 'x'.  [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared. 
#> <SQL> 'SELECT TOP 11 *
#> FROM (SELECT "x", "y", "z"
#> FROM "test" AS "LHS"
#> LEFT JOIN "#dbplyr_001" AS "RHS"
#> ON ("LHS"."x" = "RHS"."X")
#> ) "q01"'
q %>% show_query()
#> <SQL>
#> SELECT "x", "y", "z"
#> FROM "test" AS "LHS"
#> LEFT JOIN "#dbplyr_001" AS "RHS"
#> ON ("LHS"."x" = "RHS"."X")

dbRemoveTable(con, 'test')

con = odbc::dbConnect(RSQLite::SQLite(), ":memory:")

x1 = tibble(x = 'a', y = 1)
x2 = tibble(X = 'a', z = 2)

dbWriteTable(con, "test", x1, overwrite = TRUE)

q = tbl(con, "test") %>%
    left_join(x2, by = c('x' = 'X'), copy = TRUE)
q
#> Error: ambiguous column name: x
q %>% show_query()
#> <SQL>
#> SELECT `x`, `y`, `z`
#> FROM `test` AS `LHS`
#> LEFT JOIN `dbplyr_002` AS `RHS`
#> ON (`LHS`.`x` = `RHS`.`X`)

sessionInfo()
#> R version 3.6.1 (2019-07-05)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 18363)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices datasets  utils     methods   base     
#> 
#> other attached packages:
#> [1] RSQLite_2.2.2 dbplyr_2.0.0  odbc_1.3.0    dplyr_1.0.2  
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.6       knitr_1.30       magrittr_2.0.1   hms_1.0.0       
#>  [5] bit_4.0.4        tidyselect_1.1.0 R6_2.5.0         rlang_0.4.10    
#>  [9] blob_1.2.1       stringr_1.4.0    highr_0.8        tools_3.6.1     
#> [13] xfun_0.20        DBI_1.1.1        htmltools_0.5.1  ellipsis_0.3.1  
#> [17] assertthat_0.2.1 bit64_4.0.5      yaml_2.2.1       digest_0.6.27   
#> [21] tibble_3.0.4     lifecycle_0.2.0  crayon_1.3.4     purrr_0.3.4     
#> [25] vctrs_0.3.6      memoise_1.1.0    glue_1.4.2       evaluate_0.14   
#> [29] rmarkdown_2.6    stringi_1.5.3    compiler_3.6.1   pillar_1.4.7    
#> [33] generics_0.1.0   renv_0.11.0      pkgconfig_2.0.3
```

<sup>Created on 2021-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment] 2021-01-21 19:21
Yes, because the error clearly happens because 2.0.0 reduces the complexity of the generated query. It is only going to cause problems if you have column names that only differ in case, which should (I would hope) be rare in practice. So it's a minor inconvenience at the cost of much clearer SQL for most people.

**Comment by awong234** [comment] 2021-01-21 20:19
Ok thank you!

**Comment by hadley** [comment] 2021-01-21 21:58
I'm going to close this issue, but it's still indexed by google, so if other people hit it, they'll be able to find it, and we can consider reopen it if it turns out to be a common problem. Thanks for reporting and I'm sorry we couldn't help more 😞.

**Closed by hadley** 2021-01-21 21:58 UTC
Labels: reprex

**Comment by awong234** [comment] 2021-01-22 00:05
Thank you Hadley, no worries, in most cases it will be but an inconvenience as you mention. I think others who make use of `janitor::clean_names()` and `dbplyr` frequently as I have may run into this issue, but otherwise easy enough to avoid.

**Comment by PauloJhonny** [comment] 2021-09-09 19:05
Hey, I'm facing the same issue when using dbplyr 2.1.1 and SQL Server. The problem is gone when I use dbplyr 1.4.3. I tried to join two tables where the column id names are the following:

'idcontrato' and 'idContrato'

For the time being, I will downgrade the dbplyr version because I can't change the column names in database side.

Thank you.
