### ISSUE TITLE
purr-style lambdas do not work in across() within dbplyr

### ISSUE THREAD

**Issue by kmishra9** [tidyverse/dbplyr#491] opened 2020-08-15 22:27 UTC
I would use `drop_na()` for this pattern but in absence of support for `dbplyr`, would need to use `filter` along with the newly superseding `across()`. When you take out the lambda, the generated SQL isn't translated quite correctly (i.e. `everything()` is not a recognized SQL function.

``` r
library("dplyr", warn.conflicts = FALSE)
#> Warning: package 'dplyr' was built under R version 3.6.2

lf <- dbplyr::lazy_frame(x = c(1:10, NA), con = dbplyr::simulate_postgres())

lf %>% 
    filter(across(everything(), ~ !is.na(.)))
#> <SQL>
#> Error in UseMethod("escape"): no applicable method for 'escape' applied to an object of class "formula"

lf %>% 
    filter(across(everything(), !is.na(cur_column())))
#> <SQL>
#> SELECT *
#> FROM `df`
#> WHERE (across(everything(), NOT(((cur_column()) IS NULL))))
```

<sup>Created on 2020-08-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment] 2020-09-16 19:43
Duplicate of #480

**Closed by hadley** 2020-09-16 19:43 UTC
