### ISSUE TITLE
Using %in% filter with a character vector failing when table SQL table is using columnstore

### ISSUE THREAD

**Issue by schradj** [tidyverse/dbplyr#1059] opened 2022-12-01 06:06 UTC
Can't show actual example but, here's basically what I'm doing.
Began using ColumnStore for some of the larger tables in our datawarehouse.  Since the change, using the %in% operator with a character vector to filter the table to a subset of values in a column began returning an error.

Still works with datawarehouses where ColumnStore is not being used.

```
dbi_conn <- DBI::dbConnect( 
                         RMariaDB::MariaDB(), 
                         hostname = "MyMariaDBHostName", 
                         dbname = "FruitData_dw")  

lzy_qry <- dplyr::tbl(dbi_conn ,dplyr::sql("SELECT * FROM FruitData"))  

lzy_qry
# Source:   SQL [?? x 4]
# Database: mysql  [@MyMariaDBHostName:NA/FruitData_dw]
   FruitName           FruitCode           Color           
  <char>                 <int>                  <char>
  "Apple"                 1                         "Red"
  "Banana"               3                         "Yellow"
  "Mango"               4                        "Yellow"
  "Orange"               5                           "Orange"
… with more rows

list <- c("Apple", "Banana", "Orange")  

lzy_qry %>% filter(FruitCode %in% c(1,3,5))  # works  

lzy_qry %>% filter(FruitName %in% list )  # ERROR  
lzy_qry %>% filter(FruitName %in% c("Apple", "Banana", "Orange"))  # ERROR  
```

Error: Internal error: CrossEngineStep::execute() fatal error runing mysql_real_query() in libmysql_client lib (1054) (Unknown column 'q01.[ColumnName]' in 'where clause') [1815]

**Comment by mgirlich** [comment] 2022-12-01 07:22
The formatting of your reprex is quite hard to read. Please make it more readable.

I don' know what ColumnStore but the error message you included clearly shows that you refer to a column `[ColumnName]` which does not exist. Maybe you provided the wrong reprex?

**Comment by schradj** [comment] 2022-12-01 14:59
Apologies,

Can't show actual output, so I'm just making up some dummy code.
I've cleaned up the example as much as I can, removed the propbably poorly formatted pseudocode and just using a notional column name "FruitName" in a notional table "FruitData" in an SQL data warehouse using MariaDB ColumnStore
https://mariadb.com/kb/en/mariadb-columnstore/

Thanks

**Comment by mgirlich** [comment] 2022-12-01 15:35
And what's the error you get?

By the way, when you create an issue we link to an information page on how to create a reprex

> Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>. You can use the examples in [Reprexes for dbplyr](https://dbplyr.tidyverse.org/articles/reprex.html) as a starting point for your reprex.

Making a proper reprex would really help. Please also test out if you can reproduce this with a `memdb_frame()`.

**Comment by schradj** [comment] 2022-12-01 17:18
The error I get is

"Error: Internal error: CrossEngineStep::execute() fatal error runing mysql_real_query() in libmysql_client lib (1054) (Unknown column 'q01.FruitName' in 'where clause') [1815]

Can't recreate it with memdb_frame() as this is only an issue with a MariaDB datawarehouse with ColumnStore enabled.

Can't share a screenshot of actual table and data for security reasons with the actual database.

The example I've given is an exact copy of the code I'm using but the table name and the column name is made up.

When the exact same datawarehouse is built without ColumnStore enabled, the same code runs without error and returns the correctly filtered data.

Filtering an <int> field using the %in% operator seems to work fine even with ColumnStore enabled

Issue appears to be with a <char> field when the table is using ColumnStore.
This code ....
` lzy_qry %>% filter(FruitName %in% c("Apple", "Banana", "Orange")) # ERROR `

gives me this error...
Error: Internal error: CrossEngineStep::execute() fatal error runing mysql_real_query() in libmysql_client lib (1054) (Unknown column 'q01.FruitName' in 'where clause') [1815]

This code ...
`lzy_qry %>% filter(FruitName == "Apple") 

correctly returns the results of the lazy query with only records where the FruitName column is "Apple"

This code ...
`lzy_qry %>% filter(FruitCode %in%  c(1,3)) 

also correctly returns the results of the lazy query with only records where the FruitCode column is either 1 or 3

So,  it appears it is only the %in% operator on a character field for a table in a SQL/MariaDB datawarehouse with ColumnStore enabled

**Comment by mgirlich** [comment] 2022-12-02 05:12
Can you show the generated query of your 3 queries:

```r
lzy_qry %>% filter(FruitName %in% c("Apple", "Banana", "Orange")) %>% show_query()
lzy_qry %>% filter(FruitName == "Apple") %>% show_query()
lzy_qry %>% filter(FruitCode %in% c(1,3)) %>% show_query()
```

**Comment by schradj** [comment] 2022-12-15 04:24
<SQL> SELECT * FROM (SELECT * FROM FruitData) `q01`WHERE (`FruitName` IN ('Apple', 'Banana', 'Orange')) <- error
Error: Internal error: CrossEngineStep::execute() fatal error runing mysql_real_query() in libmysql_client lib (1054) (Unknown column 'q01.FruitName' in 'where clause') [1815]

<SQL> SELECT * FROM (SELECT * FROM FruitData) `q01`WHERE (`FruitName` = 'Apple') <- works

<SQL> SELECT * FROM (SELECT * FROM FruitData) `q01`WHERE (`FruitCode` IN (1,3)) <- error
Error: Internal error: CrossEngineStep::execute() fatal error runing mysql_real_query() in libmysql_client lib (1054) (Unknown column 'q01.FruitCode' in 'where clause') [1815]

**Comment by mgirlich** [comment] 2023-01-25 08:09
Closing this as I can't reproduce this issue, a proper reprex is missing and it seems to be very specific.

**Closed by mgirlich** 2023-01-25 08:09 UTC
Labels: reprex
