### ISSUE TITLE
Can we add custom translations ?

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/dbplyr#1341] opened 2023-07-31 10:54 UTC
In `sql_substr()` we have an example showing us how to add a new variant.

I think I understand the general mechanism, `sql_variant()` receives  "translators" which are environments containing functions creating strings of class "sql". I see also that `sql_translator()` has a `.parent` arg so we can inherit from a higher level translator.

But I don't quite understand how to idiomatically add a new translation to an existing variant. 

A hack that I think will work OK for my project is to edit the `base_odbc_scalar`, `base_odbc_agg`, and `base_odbc_win` environments directly since they're exported and not locked, another would be to overwrite `dbplyr:::sql_translation.Oracle` (Since that's Oracle in my case) but seems a bit clunky as well.

I thought about using a super class of my "Oracle" too but it seems I'd have to set new methods for at least `tbl()` and probably more, that seems like a rabbit hole.

My use case FWIW is to add a series of functions such as `count_if()`, which don't exist in neither R or Oracle, I'd like also to implement some translations from str_replace to REGEXP_EXTRACT, the general idea is that I'd like this code to work the same before or after collecting.

Can you recommend a way to go at this ?

**Comment by moodymudskipper** [comment] 2023-07-31 20:37
Might be a duplicate of #247

**Comment by hadley** [comment] 2023-12-19 22:20
Duplicate of #309. Still don't have any good model for how we should implement this 😞

**Closed by hadley** 2023-12-19 22:20 UTC
Labels: feature
