### ISSUE TITLE
Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ", : Unable to retrieve JDBC result set for SELECT * FROM "schema".table_name AS "zzz50" WHERE (0 = 1) (ORA-00933: SQL command not properly ended )

### ISSUE THREAD

**Issue by fahadshery** [tidyverse/dbplyr#340] opened 2019-08-02 17:16 UTC
Getting this error when executing the following code:

```r
library(RJDBC)
jdbcDriver =JDBC("oracle.jdbc.OracleDriver",classPath="C:/Program Files (x86)/Oracle/instantclient_12_2/ojdbc7.jar")
jdbcConnection =dbConnect(jdbcDriver, "jdbc:oracle:thin:@//localhost:port/instance_name", user = "", password = "")
my_tbl <- tbl(con, in_schema('"schema_name"', "table_name")) 
```

**Comment by fahadshery** [comment] 2019-08-02 17:18
corrected last line of code
```r
my_tbl <- tbl(jdbcConnection, in_schema('"schema_name"', "table_name")) 
```

**Comment by hadley** [comment] 2019-12-13 19:58
Duplicate of #359

**Closed by hadley** 2019-12-13 19:58 UTC
