### ISSUE TITLE
Warning `lang_name()` is deprecated as of rlang 0.2.0 for lazy data frame

### ISSUE THREAD

**Issue by mskyttner** [tidyverse/dbplyr#375] opened 2019-11-19 10:14 UTC
If filtering a lazy data frame a warning is displayed about usage of deprecated `rlang::lang_name()` functions. This might be related to #328  or even be a dupe of that one. Doing `collect` before the filter makes the warning go away. 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(dbplyr)
#> 
#> Attaching package: 'dbplyr'
#> The following objects are masked from 'package:dplyr':
#> 
#>     ident, sql

# a filtered lazy data frame
filtered <-
  lazy_frame(x = c(1:10, NA)) %>% 
  filter(x < max(x, na.rm = TRUE))

filtered
#> <SQL>
#> Warning: `lang_name()` is deprecated as of rlang 0.2.0.
#> Please use `call_name()` instead.
#> This warning is displayed once per session.
#> Warning: `lang()` is deprecated as of rlang 0.2.0.
#> Please use `call2()` instead.
#> This warning is displayed once per session.
#> SELECT `x`
#> FROM (SELECT `x`, MAX(`x`) OVER () AS `zzz1`
#> FROM `df`) `dbplyr_001`
#> WHERE (`x` < `zzz1`)

# this quosure seems to contain this expression
q <- filtered %>% purrr::pluck("ops", "dots", 1)
q
#> <quosure>
#> expr: ^x < max(x, na.rm = TRUE)
#> env:  0x5590a7ed0318

e <- rlang::quo_get_expr(q)
testthat::capture_output(str(e))
#> [1] " language x < max(x, na.rm = TRUE)"
```

Is somehow somewhere the evaluation of the expression in the quosure making a call into the deprecated rlang::lang\* fcns (since rlang 0.2) instead of using rlang::call2?

The docs for rlang::call2() mentions:

  - “In rlang 0.2.0 lang() was soft-deprecated and renamed to call2().”
  - “In early versions of rlang calls were called”language" objects in order to follow the R type nomenclature as returned by base::typeof(). The goal was to avoid adding to the confusion between S modes and R types. With hindsight we find it is better to use more meaningful type names."

``` r
sessionInfo()
#> R version 3.6.1 (2019-07-05)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Linux Mint 19.2
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
#> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=sv_SE.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=sv_SE.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=sv_SE.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] dbplyr_1.4.2 dplyr_0.8.3 
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.3       knitr_1.25       magrittr_1.5     tidyselect_0.2.5
#>  [5] R6_2.4.0         rlang_0.4.1      stringr_1.4.0    highr_0.8       
#>  [9] tools_3.6.1      xfun_0.10        DBI_1.0.0        withr_2.1.2     
#> [13] htmltools_0.4.0  yaml_2.2.0       assertthat_0.2.1 digest_0.6.22   
#> [17] tibble_2.1.3     crayon_1.3.4     purrr_0.3.3      testthat_2.2.1  
#> [21] glue_1.3.1       evaluate_0.14    rmarkdown_1.16   stringi_1.4.3   
#> [25] compiler_3.6.1   pillar_1.4.2     pkgconfig_2.0.3
```

<sup>Created on 2019-11-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment] 2019-12-13 19:36
Duplicate of #328

**Closed by hadley** 2019-12-13 19:36 UTC
