### ISSUE TITLE
Implementation of Oracle's 'CONNECT BY' clause as dplyr verbs.

### ISSUE THREAD

**Issue by pepijn-devries** [tidyverse/dbplyr#1107] opened 2023-01-21 16:19 UTC
Currently, I'm working with an Oracle database with tables containing hierarchies. I'm using SQL clauses `CONNECT BY` in combination with `PRIOR` to obtain the hierarchical information recursively. Using SQL directly (wrapped in `dbplyr::sql`) with `tbl` allows me to obtain the hierarchical info. However, dbplyr generates invalid SQL queries when I join the `tbl` with other `tbl`s obtained from the database using dplyr verbs.

I have noticed that `select_query` has support for `group_by` and `order_by`, but not for `connect_by`. Could this be implemented as feature? If not, what would be the preferred route to work around this?

It's hard to provide a proper reprex without a database, hopefully this is helpful. Consider this code:
```
## con is a connection to a specific Oracle database
tab <- dplyr::tbl(
  con, dplyr::sql(
    paste(
      "SELECT",
      "\"SPE_ID\",",
      "\"SSE_ID\" AS ROOT_ID,",
      "CONNECT_BY_ROOT \"ID\" \"ID_NEST\"",
      "FROM (TABLE_A) CONNECT BY PRIOR \"ID\" = \"SSE_ID\""))
)

## This works ok
tab

## When mixing with dplyr verbs I get into trouble
dplyr::left_join(
  dplyr::tbl(con, "TABLE_B") %>% dplyr::filter(ID == 6448),
  tab,
  c(ID = "SPE_ID")
)
```
This generates the following faulty SQL:
```
<SQL>
SELECT "LHS".*, "ROOT_ID", "ID_NEST"
FROM (
  SELECT *
  FROM ("TABLE_B") 
  WHERE ("ID" = 6448.0)
) "LHS"
LEFT JOIN (SELECT "SPE_ID", "SSE_ID" AS ROOT_ID, CONNECT_BY_ROOT "ID" "ID_NEST" FROM (TABLE_A) CONNECT BY PRIOR "ID" = "SSE_ID") "SELECT ""SPE_ID"", ""SSE_ID"" AS ROOT_ID, CONNECT_BY_ROOT ""ID"" ""ID_NEST"" FROM (TABLE_A) CONNECT BY PRIOR ""ID"" = ""SSE_ID"""
  ON ("LHS"."ID" = "SELECT ""SPE_ID"", ""SSE_ID"" AS ROOT_ID, CONNECT_BY_ROOT ""ID"" ""ID_NEST"" FROM (TABLE_A) CONNECT BY PRIOR ""ID"" = ""SSE_ID"""."SPE_ID")
```
and results in:
```
Error in collect(x, n = n) : 
  Failed to collect lazy table.
Caused by error:
! nanodbc/nanodbc.cpp:1655: HY000: [Oracle][ODBC][Ora]ORA-03001: unimplemented feature
```

**Comment by mgirlich** [comment] 2023-01-23 08:07
Which dbplyr version are you using? Does this also happen with the dev version (install via `devtools::install_github("tidyverse/dbplyr")`)?

Would also be great help if you could make your reprex more minimal and even better if you could reproduce it with SQLite (as I don't have access to an Oracle DB).

**Comment by pepijn-devries** [comment] 2023-01-23 14:59
This is my current session info:

```
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=Dutch_Netherlands.1252  LC_CTYPE=Dutch_Netherlands.1252    LC_MONETARY=Dutch_Netherlands.1252
[4] LC_NUMERIC=C                       LC_TIME=Dutch_Netherlands.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_1.0.99.9000 dbplyr_2.2.1.9000

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7          plyr_1.8.6          pillar_1.8.1        compiler_4.1.1      bitops_1.0-7        class_7.3-19       
 [7] tools_4.1.1         lifecycle_1.0.3     tibble_3.1.8        gtable_0.3.0        lattice_0.20-44     pkgconfig_2.0.3    
[13] png_0.1-7           rlang_1.0.6         DBI_1.1.3           cli_3.4.1           rstudioapi_0.13     e1071_1.7-11       
[19] stringr_1.4.0       httr_1.4.3          generics_0.1.3      RgoogleMaps_1.4.5.3 vctrs_0.5.0.9000    classInt_0.4-8     
[25] grid_4.1.1          tidyselect_1.2.0    glue_1.6.2          R6_2.5.1            jpeg_0.1-9          fansi_1.0.3        
[31] sp_1.5-0            ggmap_3.0.1         tidyr_1.2.1         purrr_0.3.5         ggplot2_3.3.5       magrittr_2.0.3     
[37] scales_1.2.0        assertthat_0.2.1    colorspace_2.0-2    KernSmooth_2.23-20  utf8_1.2.2          stringi_1.7.6      
[43] proxy_0.4-27        munsell_0.5.0
```
I'll test the latest github version later today and report back. I'll also see if I can reproduce a similar issue in SQLite (note that 'connect by' is not supported by SQLite).

**Comment by pepijn-devries** [comment] 2023-01-24 19:19
I had some problems installing the github version and its dependecies. However, after installing the latest CRAN version (2.3.0), the error no longer occurs. So that issue has been resolved in the latest release. Sorry for the inconvenience.

But apart from that, it would be nice if the `CONNECT BY` clause could be supported by `dbplyr::select_query`...

**Comment by mgirlich** [comment] 2023-01-25 06:30
Closing this as the described bug is already fixed.

The `CONNECT BY` clause seems to be specific to Oracle, so I'd be very hesitant to add it to `select_query()`. A quick research suggested that `CONNECT BY` is a less powerful version of `WITH RECURSIVE`. This could then be a feature that might be worth implementing. I'll open a new issue for this.

**Closed by mgirlich** 2023-01-25 06:30 UTC
