### ISSUE TITLE
`slice_` not working with bigrquery

### ISSUE THREAD

**Issue by filipemsc** [tidyverse/dbplyr#1005] opened 2022-09-12 17:04 UTC
I was trying to use `slice_sample` with a big query table, but it did not work. apparently, there is a syntax error when translating the dplyr function to SQL. 

``` r
library(dplyr)
#> Warning: package 'dplyr' was built under R version 4.1.3
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(dbplyr)
#> 
#> Attaching package: 'dbplyr'
#> The following objects are masked from 'package:dplyr':
#> 
#>     ident, sql

con <- DBI::dbConnect(drv = bigrquery::bigquery(),
               project = Sys.getenv("projectid"), 
               billing = Sys.getenv("projectid")
)

tbl(con, "basedosdados.br_ibge_inpc.mes_brasil") |>
  slice_sample(n=10) 
#> ! Using an auto-discovered, cached token.
#>   To suppress this message, modify your code or options to clearly consent to
#>   the use of a cached token.
#>   See gargle's "Non-interactive auth" vignette for more details:
#>   <https://gargle.r-lib.org/articles/non-interactive-auth.html>
#> i The bigrquery package is using a cached token for
#>   'f.matheus.cavalcanti@gmail.com'.
#> Error in `bq_job_wait()`:
#> ! Job 'projetos-bd.job_Nuu9pbzki7VYc-IdDgY_kd8QwrK_.US' failed
#> x Function not found: random; Did you mean rand? at [2:171] [invalidQuery]

#> Backtrace:
#>      x
#>   1. +-base::tryCatch(...)
#>   2. | \-base (local) tryCatchList(expr, classes, parentenv, handlers)
#>   3. |   +-base (local) tryCatchOne(...)
#>   4. |   | \-base (local) doTryCatch(return(expr), name, parentenv, handler)
#>   5. |   \-base (local) tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
#>   6. |     \-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>   7. |       \-base (local) doTryCatch(return(expr), name, parentenv, handler)
#>   8. +-base::withCallingHandlers(...)
#>   9. +-base::saveRDS(...)
#>  10. +-base::do.call(...)
#>  11. +-base (local) `<fn>`(...)
#>  12. \-global `<fn>`(input = base::quote("mid-pig_reprex.R"))
#>  13.   \-rmarkdown::render(input, quiet = TRUE, envir = globalenv(), encoding = "UTF-8")
#>  14.     \-knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
#>  15.       \-knitr:::process_file(text, output)
#>  16.         +-base::withCallingHandlers(...)
#>  17.         +-knitr:::process_group(group)
#>  18.         \-knitr:::process_group.block(group)
#>  19.           \-knitr:::call_block(x)
#>  20.             \-knitr:::block_exec(params)
#>  21.               \-knitr:::eng_r(options)
#>  22.                 +-knitr:::in_input_dir(...)
#>  23.                 | \-knitr:::in_dir(input_dir(), expr)
#>  24.                 \-knitr (local) evaluate(...)
#>  25.                   \-evaluate::evaluate(...)
#>  26.                     \-evaluate:::evaluate_call(...)
#>  27.                       +-evaluate (local) handle(...)
#>  28.                       | \-base::try(f, silent = TRUE)
#>  29.                       |   \-base::tryCatch(...)
#>  30.                       |     \-base (local) tryCatchList(expr, classes, parentenv, handlers)
#>  31.                       |       \-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>  32.                       |         \-base (local) doTryCatch(return(expr), name, parentenv, handler)
#>  33.                       +-base::withCallingHandlers(...)
#>  34.                       +-base::withVisible(value_fun(ev$value, ev$visible))
#>  35.                       \-knitr (local) value_fun(ev$value, ev$visible)
#>  36.                         \-knitr (local) fun(x, options = options)
#>  37.                           +-base::withVisible(knit_print(x, ...))
#>  38.                           +-knitr::knit_print(x, ...)
#>  39.                           \-rmarkdown:::knit_print.tbl_sql(x, ...)
#>  40.                             +-context$df_print(x)
#>  41.                             \-dbplyr:::print.tbl_sql(x)
#>  42.                               +-dbplyr:::cat_line(format(x, ..., n = n, width = width, n_extra = n_extra))
#>  43.                               | +-base::cat(paste0(..., "\n"), sep = "")
#>  44.                               | \-base::paste0(..., "\n")
#>  45.                               +-base::format(x, ..., n = n, width = width, n_extra = n_extra)
#>  46.                               \-pillar:::format.tbl(x, ..., n = n, width = width, n_extra = n_extra)
#>  47.                                 \-pillar:::format_tbl(...)
#>  48.                                   \-pillar::tbl_format_setup(...)
#>  49.                                     +-pillar:::tbl_format_setup_dispatch(...)
#>  50.                                     \-pillar:::tbl_format_setup.tbl(...)
#>  51.                                       \-pillar:::df_head(x, n + 1)
#>  52.                                         +-base::as.data.frame(head(x, n))
#>  53.                                         \-dbplyr:::as.data.frame.tbl_sql(head(x, n))
#>  54.                                           +-base::as.data.frame(collect(x, n = n))
#>  55.                                           +-dplyr::collect(x, n = n)
#>  56.                                           \-bigrquery:::collect.tbl_BigQueryConnection(x, n = n)
#>  57.                                             \-bigrquery::bq_project_query(...)
#>  58.                                               \-bigrquery::bq_job_wait(job, quiet = quiet)
#>  59.                                                 \-rlang::abort(...)


tbl(con, "basedosdados.br_ibge_inpc.mes_brasil") |>
  slice_sample(n=10) |>
  show_query()
#> <SQL>
#> SELECT `ano`, `mes`, `indice`, `variacao_mensal`, `variacao_trimestral`, `variacao_semestral`, `variacao_anual`, `variacao_doze_meses`
#> FROM (SELECT `ano`, `mes`, `indice`, `variacao_mensal`, `variacao_trimestral`, `variacao_semestral`, `variacao_anual`, `variacao_doze_meses`, ROW_NUMBER() OVER (ORDER BY random()) AS `q01`
#> FROM `basedosdados.br_ibge_inpc.mes_brasil`) `q01`
#> WHERE (`q01` <= 10)
```

<sup>Created on 2022-09-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mgirlich** [comment] 2022-09-13 06:08
Closing as this is a duplicate of this [bigrquery issue](https://github.com/r-dbi/bigrquery/issues/448).

**Closed by mgirlich** 2022-09-13 06:08 UTC
