### ISSUE TITLE
in_schema() in 2.0.0 fails with pool, but works with DBI

### ISSUE THREAD

**Issue by sheepworrier** [tidyverse/dbplyr#528] opened 2020-11-03 17:13 UTC
Since upgrading to dbplyr 2.0.0 from 1.4.4 the `in_schema()` function no longer seems to work in tandem with `tbl()` and `pool` on MSSQL.  In the example below, the conn will by default connect to the dbo schema and I am able to view tables within:

```r
# Create a pooled connection to use for all files to be loaded
conn <- dbPool(odbc::odbc(), dsn = "Data Source Name",
               database = "Database Name")
# Load the contents of a table in the default dbo schema - works fine
tbl(conn, "Table name within default dbo schema")
# Does not work when you try and use in_schema() to select a table from a different schema
tbl(conn, in_schema("Different schema name", "Table name in different schema"))
# Error in UseMethod("sql_escape_ident") : 
#  no applicable method for 'sql_escape_ident' applied to an object of class "c('Pool', 'R6')"
```
Sems to work if I use `DBI`, though, rather than `pool` so maybe the issue that needs fixing is their side?

```r
conn <- dbConnect(odbc::odbc(), dsn = "Data Source Name",
               database = "Database Name")
# Load the contents of a table in the default dbo schema - works fine
tbl(conn, "Table name within default dbo schema")
# Load the contents of a table in a different schema - works fine
tbl(conn, in_schema("Different schema name", "Table name in different schema"))
```

**Comment by hadley** [comment] 2020-11-03 17:43
Did you also upgrade pool?

**Comment by sheepworrier** [comment] 2020-11-03 17:53
> Did you also upgrade pool?

Yes 0.1.5

**Comment by calligross** [comment] 2020-11-04 18:07
I'm having the same error message, but with Postgres and I think it is related to pool 0.1.5

```R
library(pool)
library(dplyr)

con_string <- paste0("Driver={PostgreSQL ANSI};Servername=", config$server, ";Uid=", config$user, ";Pwd=", config$pass, ";Database=", config$db)
con <- dbPool(
  odbc::odbc(),
  .connection_string = con_string, timeout = 10
)

tbl(con, "ecb_fx_rate") %>% 
  left_join(
    tbl(con, "currency"),
    by = c("currency_id" = "id")
  )
```

> Error in UseMethod("sql_join_suffix") : 
  no applicable method for 'sql_join_suffix' applied to an object of class "c('Pool', 'R6')"

```
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       Ubuntu 20.04.1 LTS          
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Berlin               
 date     2020-11-04                  

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [2] CRAN (R 4.0.3)
 bit           4.0.4   2020-08-04 [2] CRAN (R 4.0.3)
 bit64         4.0.5   2020-08-30 [2] CRAN (R 4.0.3)
 blob          1.2.1   2020-01-20 [2] CRAN (R 4.0.3)
 cli           2.1.0   2020-10-12 [2] CRAN (R 4.0.3)
 crayon        1.3.4   2017-09-16 [2] CRAN (R 4.0.3)
 DBI           1.1.0   2019-12-15 [2] CRAN (R 4.0.3)
 dbplyr        2.0.0   2020-11-03 [1] CRAN (R 4.0.3)
 dplyr       * 1.0.2   2020-08-18 [2] CRAN (R 4.0.3)
 ellipsis      0.3.1   2020-05-15 [2] CRAN (R 4.0.3)
 fansi         0.4.1   2020-01-08 [2] CRAN (R 4.0.3)
 generics      0.0.2   2018-11-29 [2] CRAN (R 4.0.3)
 glue          1.4.2   2020-08-27 [2] CRAN (R 4.0.3)
 hms           0.5.3   2020-01-08 [2] CRAN (R 4.0.3)
 later         1.1.0.1 2020-06-05 [2] CRAN (R 4.0.3)
 lifecycle     0.2.0   2020-03-06 [2] CRAN (R 4.0.3)
 magrittr      1.5     2014-11-22 [2] CRAN (R 4.0.3)
 odbc          1.2.3   2020-06-18 [2] CRAN (R 4.0.3)
 pillar        1.4.6   2020-07-10 [2] CRAN (R 4.0.3)
 pkgconfig     2.0.3   2019-09-22 [2] CRAN (R 4.0.3)
 pool        * 0.1.5   2020-11-03 [1] CRAN (R 4.0.3)
 purrr         0.3.4   2020-04-17 [2] CRAN (R 4.0.3)
 R6            2.4.1   2019-11-12 [2] CRAN (R 4.0.3)
 Rcpp          1.0.5   2020-07-06 [2] CRAN (R 4.0.3)
 rlang         0.4.8   2020-10-08 [2] CRAN (R 4.0.3)
 rstudioapi    0.11    2020-02-07 [2] CRAN (R 4.0.3)
 sessioninfo   1.1.1   2018-11-05 [2] CRAN (R 4.0.3)
 tibble        3.0.4   2020-10-12 [2] CRAN (R 4.0.3)
 tidyselect    1.1.0   2020-05-11 [2] CRAN (R 4.0.3)
 vctrs         0.3.4   2020-08-29 [2] CRAN (R 4.0.3)
 withr         2.3.0   2020-09-22 [2] CRAN (R 4.0.3)`
```

With `pool 0.1.4.3`

```R
detach("package:pool", unload = TRUE)

library(pool, lib.loc = "/usr/local/lib/R/site-library")

tbl(con, "ecb_fx_rate") %>% 
  left_join(
    tbl(con, "currency"),
    by = c("currency_id" = "id")
  )
```

![image](https://user-images.githubusercontent.com/15100661/98151601-b6923c80-1ed0-11eb-8e5f-825ef52fa37a.png)

```
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       Ubuntu 20.04.1 LTS          
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Berlin               
 date     2020-11-04                  

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────
 !  package     * version date       lib source        
    assertthat    0.2.1   2019-03-21 [2] CRAN (R 4.0.3)
    bit           4.0.4   2020-08-04 [2] CRAN (R 4.0.3)
    bit64         4.0.5   2020-08-30 [2] CRAN (R 4.0.3)
    blob          1.2.1   2020-01-20 [2] CRAN (R 4.0.3)
    cli           2.1.0   2020-10-12 [2] CRAN (R 4.0.3)
    crayon        1.3.4   2017-09-16 [2] CRAN (R 4.0.3)
    DBI           1.1.0   2019-12-15 [2] CRAN (R 4.0.3)
    dbplyr        2.0.0   2020-11-03 [1] CRAN (R 4.0.3)
    dplyr       * 1.0.2   2020-08-18 [2] CRAN (R 4.0.3)
    ellipsis      0.3.1   2020-05-15 [2] CRAN (R 4.0.3)
    fansi         0.4.1   2020-01-08 [2] CRAN (R 4.0.3)
    generics      0.0.2   2018-11-29 [2] CRAN (R 4.0.3)
    glue          1.4.2   2020-08-27 [2] CRAN (R 4.0.3)
    hms           0.5.3   2020-01-08 [2] CRAN (R 4.0.3)
    later         1.1.0.1 2020-06-05 [2] CRAN (R 4.0.3)
    lifecycle     0.2.0   2020-03-06 [2] CRAN (R 4.0.3)
    magrittr      1.5     2014-11-22 [2] CRAN (R 4.0.3)
    odbc          1.2.3   2020-06-18 [2] CRAN (R 4.0.3)
    pillar        1.4.6   2020-07-10 [2] CRAN (R 4.0.3)
    pkgconfig     2.0.3   2019-09-22 [2] CRAN (R 4.0.3)
 VP pool        * 0.1.4.3 2020-11-03 [2] CRAN (R 4.0.3)
    purrr         0.3.4   2020-04-17 [2] CRAN (R 4.0.3)
    R6            2.4.1   2019-11-12 [2] CRAN (R 4.0.3)
    Rcpp          1.0.5   2020-07-06 [2] CRAN (R 4.0.3)
    rlang         0.4.8   2020-10-08 [2] CRAN (R 4.0.3)
    rstudioapi    0.11    2020-02-07 [2] CRAN (R 4.0.3)
    sessioninfo   1.1.1   2018-11-05 [2] CRAN (R 4.0.3)
    tibble        3.0.4   2020-10-12 [2] CRAN (R 4.0.3)
    tidyselect    1.1.0   2020-05-11 [2] CRAN (R 4.0.3)
    utf8          1.1.4   2018-05-24 [2] CRAN (R 4.0.3)
    vctrs         0.3.4   2020-08-29 [2] CRAN (R 4.0.3)
    withr         2.3.0   2020-09-22 [2] CRAN (R 4.0.3)

```

I hope this is useful. Otherwise I'm happy to provide additional information.

Thx and best regards
Calli

**Comment by hadley** [comment] 2020-11-04 18:31
Most useful would be a reprex using RSQLite so I can more easily start digging into the underlying cause.

**Comment by calligross** [comment] 2020-11-04 19:27
Sure, here we go:

```R
library(pool)
library(dplyr)
library(DBI)

conn <- dbConnect(RSQLite::SQLite(), dbname = ":memory:")
pool <- dbPool(RSQLite::SQLite(), dbname = "local.db")

dbWriteTable(pool, "quakes", quakes)
dbWriteTable(conn, "quakes", quakes)

tbl(conn, "quakes") %>% 
  left_join(
    tbl(conn, "quakes") 
  )

tbl(pool, "quakes") %>% 
  left_join(
    tbl(pool, "quakes") 
  )

```

<img width="579" alt="image" src="https://user-images.githubusercontent.com/15100661/98158991-1cd08c80-1edc-11eb-9020-e7cef8812eda.png">

**Comment by hadley** [comment] 2020-11-04 20:00
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session. Also, in the future, please don't include the session info unless requested — it's generally not needed and just clutters up the issue.

**Comment by calligross** [comment] 2020-11-04 20:05
Ok, just did.

**Comment by hadley** [comment] 2020-11-04 20:09
@calligross perfect, thanks!

**Comment by hadley** [comment] 2020-11-05 21:00
Somewhat more minimal reprex that illustrates both problems:

``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)

db1 <- tempfile()
db2 <- tempfile()
con <- pool::dbPool(RSQLite::SQLite(), dbname = db1)
DBI::dbExecute(con, paste0("ATTACH '", db2, "' AS aux"))
#> [1] 0
db <- copy_to(con, data.frame(x = 1:10), "df", temporary = FALSE)

left_join(db, db)
#> Joining, by = "x"
#> Error in UseMethod("sql_join_suffix"): no applicable method for 'sql_join_suffix' applied to an object of class "c('Pool', 'R6')"

copy_to(con, data.frame(x = 1:10), in_schema("aux", "df"), temporary = FALSE)
#> Error in UseMethod("sql_escape_ident"): no applicable method for 'sql_escape_ident' applied to an object of class "c('Pool', 'R6')"
```

<sup>Created on 2020-11-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by razz-matazz** [comment] 2021-01-13 11:00
Hello,

Any news on this? Is it a problem of dbplyr or of pool?

**Comment by elicit-bergmann** [comment] 2021-01-13 20:27
In case another simpler example helps
``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)
pool_object <- pool::poolCreate(simulate_dbi)
as.sql(in_schema("asdf", "qwer"), pool_object)
#> Error in UseMethod("sql_escape_ident"): no applicable method for 'sql_escape_ident' applied to an object of class "c('Pool', 'R6')"
```

<sup>Created on 2021-01-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment] 2021-01-18 18:44
Fixed in pool 0.1.6 (on CRAN now) 😄

**Closed by hadley** 2021-01-18 18:44 UTC

**Comment by razz-matazz** [comment] 2021-01-19 09:13
Hello, 
I still run into 
```Error in UseMethod("sql_escape_ident") : 
  no applicable method for 'sql_escape_ident' applied to an object of class "c('Pool', 'R6')"
```

**Comment by hadley** [comment] 2021-01-19 12:46
@razz-matazz please close all open R sessions and install pool. If that doesn't, work please provide a reprex.

**Comment by atungate** [comment] 2021-01-26 02:20
Here is a reprex using elicit-bergmann's example. I closed all R sessions, installed pool from CRAN, closed all R sessions, and still ran into the issue. I even restarted my computer to be sure :). Let me know if you want any other info (OS, `sessionInfo()`, etc.).

``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)
pool_object <- pool::poolCreate(simulate_dbi)
as.sql(in_schema("asdf", "qwer"), pool_object)
#> Error in UseMethod("sql_escape_ident"): no applicable method for 'sql_escape_ident' applied to an object of class "c('Pool', 'R6')"
```

<sup>Created on 2021-01-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment] 2021-01-26 12:47
Why are you calling `as.sql()`?

**Comment by elicit-bergmann** [comment] 2021-01-26 15:30
Because I was trying to create a reprex that didn't depend on running a database. The simulation functions seemed the way to go and the `tbl` function failed for the `simulate_dbi` connection for other reasons and I didn't want to make the example even more complex by building additional support functions to get past this:
``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)
pool_object <- pool::poolCreate(simulate_dbi)
tbl(pool_object, in_schema("asdf", "qwer"))
#> Error in (function (classes, fdef, mtable) : unable to find an inherited method for function 'dbGetQuery' for signature '"TestConnection", "sql"'
```

<sup>Created on 2021-01-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

And while trying to debug this myself I found the `as.sql` function failing as I descended through other functions, so it seemed to me that it would provide a straightforward example of the problem.

Here is a version that fails with `translate_sql`. We are using `translate_sql` as part of a framework for capturing metadata from a {dbplyr} ETL pipeline.

``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)
translate_sql(x + 1, con = pool::poolCreate(simulate_dbi))
#> Error in UseMethod("sql_escape_ident"): no applicable method for 'sql_escape_ident' applied to an object of class "c('Pool', 'R6')"
```

<sup>Created on 2021-01-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment] 2021-01-26 17:46
@elicit-bergmann see my reprex above, which works fine for me now:

``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)

db1 <- tempfile()
db2 <- tempfile()
con <- pool::dbPool(RSQLite::SQLite(), dbname = db1)
DBI::dbExecute(con, paste0("ATTACH '", db2, "' AS aux"))
#> [1] 0
db <- copy_to(con, data.frame(x = 1:2), "df", temporary = FALSE)

left_join(db, db)
#> Joining, by = "x"
#> # Source:   lazy query [?? x 1]
#> # Database: sqlite 3.34.1 [/tmp/RtmpAYT6Hs/file112f6e5461ac]
#>       x
#>   <int>
#> 1     1
#> 2     2
copy_to(con, data.frame(x = 1:2), in_schema("aux", "df"), temporary = FALSE)
#> # Source:   table<`aux`.`df`> [?? x 1]
#> # Database: sqlite 3.34.1 [/tmp/RtmpAYT6Hs/file112f6e5461ac]
#>       x
#>   <int>
#> 1     1
#> 2     2
```

<sup>Created on 2021-01-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

The way that method dispatch wends between pool, dplyr, and dbplyr is complex, so unfortunately finding arbitrary functions that don't work doesn't provide me with useful data.

**Comment by elicit-bergmann** [comment] 2021-01-26 19:57
Got it. Here is a reprex starting with your `RSQLite` code. This is a minimal example of how we are using `sql_translate` to capture information which is later used in a data dictionary. 

``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)

db1 <- tempfile()
db2 <- tempfile()

# a straight connection produces no error
# con <- DBI::dbConnect(RSQLite::SQLite(), dbname = db1)

con <- pool::dbPool(RSQLite::SQLite(), dbname = db1)
DBI::dbExecute(con, paste0("ATTACH '", db2, "' AS aux"))
#> [1] 0
db <- copy_to(con, data.frame(x = 1:2), "df", temporary = FALSE)

left_join(db, db)
#> Joining, by = "x"
#> # Source:   lazy query [?? x 1]
#> # Database: sqlite 3.34.1
#> #   [/var/folders/4y/s4tk9hn97c78hvh5n5bmk73h0000gn/T//RtmpjPEnL2/file531a6a8b85d2]
#>       x
#>   <int>
#> 1     1
#> 2     2
copy_to(con, data.frame(x = 1:2), in_schema("aux", "df"), temporary = FALSE)
#> # Source:   table<`aux`.`df`> [?? x 1]
#> # Database: sqlite 3.34.1
#> #   [/var/folders/4y/s4tk9hn97c78hvh5n5bmk73h0000gn/T//RtmpjPEnL2/file531a6a8b85d2]
#>       x
#>   <int>
#> 1     1
#> 2     2

# We create an ETL specification class
etl_spec <- list()
attr(etl_spec, "class") <- "spec"

# We start with a source table
etl_spec$table <- tbl(con, in_schema("aux", "df"))

# We overload the mutate function so we can extract the statements
mutate.spec <- function(.spec, ...) {
  # capture the mutate statements
  attributes <- rlang::dots_definitions(...)$dots
  
  # extract both dplyr and sql code to be used later in a data dictionary
  .spec$attribute_df <- tibble(attribute_name = names(attributes), attributes) %>%
    mutate(attribute_sql = purrr::map_chr(attributes, translate_sql, con = remote_con(.spec$table), window=FALSE),
           attribute_dplyr = purrr::map_chr(attributes, rlang::quo_text))
  
  # add the mutate to the table  
  .spec$table <- .spec$table %>% 
    dplyr::mutate(!!!attributes)
  return(.spec)
}

etl_spec %>% 
  mutate(y = x^2 + 1)
#> Error: Problem with `mutate()` input `attribute_sql`.
#> x no applicable method for 'sql_escape_ident' applied to an object of class "c('Pool', 'R6')"
#> ℹ Input `attribute_sql` is `purrr::map_chr(...)`.
```

<sup>Created on 2021-01-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment] 2021-01-26 21:05
@elicit-bergmann can you please file that as a new issue? This is not at all related to the original issue.
