### ISSUE TITLE
dbplyr 2.4.0 - connecting to a table via a database link no longer works

### ISSUE THREAD

**Issue by mgarbuzov** [tidyverse/dbplyr#1445] opened 2024-02-06 16:36 UTC
This connection still works in 2.3.4, doesn't work since 2.4.0.
```r
tbl(con, from = in_schema("MY_SCHEMA", sql("MY_TABLE@MY_DB_LINK")))
```

```r
Error in `db_query_fields.DBIConnection()`:
! Can't query fields.
Caused by error:
! nanodbc/nanodbc.cpp:1710: 42S02
[Oracle][ODBC][Ora]ORA-00942: table or view does not exist
 
Run `rlang::last_trace()` to see where the error occurred.
> rlang::last_trace()
<error/rlang_error>
Error in `db_query_fields.DBIConnection()`:
! Can't query fields.
Caused by error:
! nanodbc/nanodbc.cpp:1710: 42S02
[Oracle][ODBC][Ora]ORA-00942: table or view does not exist
 
---
Backtrace:
     ▆
  1. ├─dplyr::tbl(con, from = in_schema("MY_SCHEMA", sql("MY_TABLE@MY_DB_LINK")))
  2. └─dplyr:::tbl.DBIConnection(con, from = in_schema("MY_SCHEMA", sql("MY_TABLE@MY_DB_LINK")))
  3.   ├─dplyr::tbl(...)
  4.   └─dbplyr:::tbl.src_dbi(...)
  5.     └─dbplyr::tbl_sql(c(subclass, "dbi"), src = src, from = from, ...)
  6.       ├─vars %||% dbplyr_query_fields(src$con, from)
  7.       └─dbplyr:::dbplyr_query_fields(src$con, from)
  8.         └─dbplyr:::dbplyr_fallback(con, "db_query_fields", ...)
  9.           ├─rlang::eval_bare(expr((!!fun)(con, ...)))
 10.           └─dbplyr:::db_query_fields.DBIConnection(con, ...)
Run rlang::last_trace(drop = FALSE) to see 6 hidden frames.
```

**Comment by hadley** [comment] 2024-02-14 18:38
What is a database link?

**Comment by mgarbuzov** [comment] 2024-02-15 11:18
@hadley if you have two databases, you can set up a link between them. Then, when you're connected to Database A, you can query tables in Database B via the link by including `table_name@link_name` (see [here](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/CREATE-DATABASE-LINK.html#GUID-D966642A-B19E-449D-9968-1121AF06D793)). The problem is, I was able to do this in dbplyr 2.3.4 by wrapping the table name with the link in `sql()`, but it stopped working since 2.4.0.

**Comment by hadley** [comment] 2024-02-15 13:20
Yeah, looks like a duplicate of #1388, which I'm working on now.

**Closed by hadley** 2024-02-15 13:20 UTC
