### ISSUE TITLE
Problem to filter dates with Sqlite database

### ISSUE THREAD

**Issue by tisseuil** [tidyverse/dbplyr#1356] opened 2023-08-22 10:34 UTC
Hi, 

I do not manage to filter dates from an SQlite database. Any suggestions ? Thanks

```r
library(dplyr)
con <- dbConnect(RSQLite::SQLite(), ":memory:",extended_types = TRUE)
df = data.frame(
  start_dates = as.Date(c('2020-01-31', '2020-02-28', '2020-03-31')))
db_copy_to(con,"df",df,overwrite = TRUE)

tbl(con,"df") %>%
  filter(start_dates == '2020-01-31')
```

**Comment by hadley** [comment] 2023-11-02 19:53
I'm not sure how much we can do here because this is tangled up in SQLite's partial support for dates. Even manually using the sqlite `DATE()` function, I couldn't get it to do what I wanted:

``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)
library(DBI)

con <- dbConnect(RSQLite::SQLite(), ":memory:", extended_types = TRUE)
df <- data.frame(x = as.Date(c('2020-01-31', '2020-02-28', '2020-03-31')))
dbWriteTable(con, "df", df)

db <- tbl(con,"df") 
db |> mutate(x, jan31 = DATE('2020-01-31'), equal = x == DATE('2020-01-31'))
#> # Source:   SQL [3 x 3]
#> # Database: sqlite 3.41.2 [:memory:]
#>   x          jan31      equal
#>   <date>     <chr>      <int>
#> 1 2020-01-31 2020-01-31     0
#> 2 2020-02-28 2020-01-31     0
#> 3 2020-03-31 2020-01-31     0
```

And I could only get the correct results through trickery:

```R
db |> filter(x == local(as.integer(as.Date('2020-01-31')))) 
#> # Source:   SQL [1 x 1]
#> # Database: sqlite 3.41.2 [:memory:]
#>   x         
#>   <date>    
#> 1 2020-01-31
```

<sup>Created on 2023-11-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Hmmm, maybe the problem is the SQLite wants **Julian** days (the fractional number of days since noon in Greenwich on November 24, 4714 B.C), and we're giving it epoch days. I suspect that might be an issue that needs to be resolved in RSQLite.

**Comment by hadley** [comment] 2023-11-02 21:06
Ok, I have no idea how you're supposed to do this with raw SQL, so I think it's out of scope for dbplyr; this is some SQLite weirdness.

``` r
library(DBI)

con <- dbConnect(RSQLite::SQLite(), ":memory:", extended_types = TRUE)
df <- data.frame(x = as.Date(c('1970-01-01')))
dbWriteTable(con, "df", df)

dbGetQuery(con, "SELECT * FROM df")
#>            x
#> 1 1970-01-01
dbGetQuery(con, "SELECT * FROM df WHERE x = '1970-01-01'")
#> [1] x
#> <0 rows> (or 0-length row.names)
dbGetQuery(con, "SELECT * FROM df WHERE x = DATE('1970-01-01')")
#> [1] x
#> <0 rows> (or 0-length row.names)
dbGetQuery(con, "SELECT * FROM df WHERE DATE(x) = DATE('1970-01-01')")
#> [1] x
#> <0 rows> (or 0-length row.names)
dbGetQuery(con, "SELECT * FROM df WHERE x = JULIANDAY('1970-01-01')")
#> [1] x
#> <0 rows> (or 0-length row.names)
dbGetQuery(con, "SELECT * FROM df WHERE JULIANDAY(x) = JULIANDAY('1970-01-01')")
#> [1] x
#> <0 rows> (or 0-length row.names)
```

<sup>Created on 2023-11-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Closed by hadley** 2023-11-02 21:06 UTC
