### ISSUE TITLE
Support BigQuery column naming conventions

### ISSUE THREAD

**Issue by blairj09** [tidyverse/dbplyr#254] opened 2019-03-05 18:31 UTC
In BigQuery, `.` are not allowed in column names. The default `dplyr` join behavior is to distinguish identical column names with the `.x` and `.y` suffix. This breaks `dplyr` joins in BigQuery.

The user could certainly update the `suffix` argument to join calls so that joins work (for example, `suffix = c("_x", "_y")` works). However, it would be nice if `dbplyr` contained a translation layer for BigQuery that took care of this.

BigQuery ODBC connections have class `BigQuery`

**Comment by hadley** [comment] 2019-03-05 19:26
Duplicate of #214

**Closed by hadley** 2019-03-05 19:26 UTC
