### ISSUE TITLE
Backend: Sybase

### ISSUE THREAD

**Issue by imanuelcostigan** [tidyverse/dbplyr#215] opened 2019-01-13 21:05 UTC
Is there any appetite to develop a Sybase backend? How easy / hard would it be to provision a Sybase test environment?

**Comment by hadley** [comment] 2019-01-14 16:03
I'd be happy to review a PR.  

I'm in the process of a bunch of refactoring (code and test) that should make a test environment much less important by relying on regression tests of SQL output. rstudio::conf will take up the rest of the week, and but I should be able to finish it off the week of Jan 21.

**Comment by imanuelcostigan** [comment] 2019-01-15 07:38
I’ll come back to this ticket at that point.

**Comment by hadley** [comment] 2019-02-05 16:33
I've completed the major reshuffling if you want to come back to it.

**Comment by hadley** [comment] 2019-02-05 16:34
I'll be working on dbplyr for the next 2-3 weeks, so should be able to give rapid feedback on PRs.

**Comment by hadley** [comment] 2020-09-17 13:36
Closing this because we've made no progress in well over a year.

**Closed by hadley** 2020-09-17 13:36 UTC
Labels: feature, func trans :earth_africa:, verb trans :robot:
