### ISSUE TITLE
Error creating temp table in SQL Server

### ISSUE THREAD

**Issue by tonyk7440** [tidyverse/dbplyr#445] opened 2020-05-07 21:24 UTC
I'm running into an error when running code like the following:

```
my_view %>% 
  inner_join(my_example, copy = TRUE)
```
```
Created a temporary table named: #dbplyr_001
Error in result_insert_dataframe(rs@ptr, values) : 
  nanodbc/nanodbc.cpp:1587: 42S02: [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name '#dbplyr_001'. 
```

I thought it might be a permissions issue but it seems like it is not as I can create a temp table directly using
```
Create Table #dbplyr_001 (
    EmployeeID int
);

Select EmployeeID from #dbplyr_001

Drop Table #dbplyr_001
````

In the process of creating a reprex for this I seem to have run into another issue using the `inner_join` command where it seems to be not finding the common variables.

``` r
library(tibble)
library(dbplyr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:dbplyr':
#> 
#>     ident, sql
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

# Remote view
my_view <- tibble(item_category = c("A", "B", "C"),
                  item = c("toy", "book", "car"),
                  value = c(4, 5, 10))

# Small local data
my_example <- tibble(item_category = c("A", "B"),
                     item = c("toy", "book"))

# Execute remote join
lazy_frame(x = my_view, con = simulate_mssql()) %>%
  inner_join(my_example, copy = TRUE) %>%
  show_query()
#> `by` required, because the data sources have no common variables
```

<sup>Created on 2020-05-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.5.3 (2019-03-11)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United Kingdom.1252 
#>  ctype    English_United Kingdom.1252 
#>  tz       Europe/London               
#>  date     2020-05-07                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.5.3)
#>  backports     1.1.4   2019-04-10 [1] CRAN (R 3.5.3)
#>  callr         3.1.1   2018-12-21 [1] CRAN (R 3.5.2)
#>  cli           1.1.0   2019-03-19 [1] CRAN (R 3.5.3)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.1)
#>  DBI           1.0.0   2018-05-02 [1] CRAN (R 3.5.3)
#>  dbplyr      * 1.4.3   2020-04-19 [1] CRAN (R 3.5.3)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 3.5.1)
#>  devtools      2.0.2   2019-04-08 [1] CRAN (R 3.5.3)
#>  digest        0.6.18  2018-10-10 [1] CRAN (R 3.5.2)
#>  dplyr       * 0.8.3   2019-07-04 [1] CRAN (R 3.5.3)
#>  evaluate      0.13    2019-02-12 [1] CRAN (R 3.5.2)
#>  fs            1.3.1   2019-05-06 [1] CRAN (R 3.5.3)
#>  glue          1.3.1   2019-03-12 [1] CRAN (R 3.5.3)
#>  highr         0.7     2018-06-09 [1] CRAN (R 3.5.1)
#>  htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.5.1)
#>  knitr         1.27    2020-01-16 [1] CRAN (R 3.5.3)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.5.1)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.5.1)
#>  pillar        1.3.1   2018-12-15 [1] CRAN (R 3.5.2)
#>  pkgbuild      1.0.2   2018-10-16 [1] CRAN (R 3.5.2)
#>  pkgconfig     2.0.2   2018-08-16 [1] CRAN (R 3.5.2)
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.5.2)
#>  prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.5.1)
#>  processx      3.2.1   2018-12-05 [1] CRAN (R 3.5.2)
#>  ps            1.3.0   2018-12-21 [1] CRAN (R 3.5.2)
#>  purrr         0.3.3   2019-10-18 [1] CRAN (R 3.5.3)
#>  R6            2.4.0   2019-02-14 [1] CRAN (R 3.5.2)
#>  Rcpp          1.0.1   2019-03-17 [1] CRAN (R 3.5.3)
#>  remotes       2.0.4   2019-04-10 [1] CRAN (R 3.5.3)
#>  rlang         0.4.0   2019-06-25 [1] CRAN (R 3.5.3)
#>  rmarkdown     2.1     2020-01-20 [1] CRAN (R 3.5.3)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.5.1)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.2)
#>  stringi       1.4.3   2019-03-12 [1] CRAN (R 3.5.3)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.5.2)
#>  testthat      2.0.1   2018-10-13 [1] CRAN (R 3.5.2)
#>  tibble      * 2.1.1   2019-03-16 [1] CRAN (R 3.5.3)
#>  tidyselect    0.2.5   2018-10-11 [1] CRAN (R 3.5.2)
#>  usethis       1.5.1   2019-07-04 [1] CRAN (R 3.5.3)
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.5.1)
#>  xfun          0.12    2020-01-13 [1] CRAN (R 3.5.3)
#>  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.5.1)
#> 
#> [1] C:/Users/akenny/Documents/R/win-library/3.5
#> [2] C:/Program Files/R/R-3.5.3/library
```

</details>

**Comment by saishton** [comment] 2020-05-11 12:34
The first half of this is the same as #438 - there's a temporary workaround mentioned in there.

**Comment by hadley** [comment] 2020-05-15 14:33
Duplicate of #438

**Closed by hadley** 2020-05-15 14:33 UTC
