### ISSUE TITLE
Cannot use `if` in `filter()` with Oracle/odbc

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/dbplyr#1180] opened 2023-03-06 10:55 UTC
The following idiom works with SQLite:

```
foo <- dbplyr::memdb_frame(cars)
dplyr::filter(foo, if (TRUE) TRUE else TRUE)
#> # Source:   SQL [?? x 2]
#> # Database: sqlite 3.39.4 [:memory:]
#>    speed  dist
#>    <dbl> <dbl>
#>  1     4     2
#>  2     4    10
#>  3     7     4
#>  4     7    22
#>  5     8    16
#>  6     9    10
#>  7    10    18
#>  8    10    26
#>  9    10    34
#> 10    11    17
#> # … with more rows
```

But no luck with Oracle using ODBC driver :

```
bar <- tbl(connect_to_db(), dbplyr::in_schema("DATA_MART", "D_PRODUKT_V"))
dplyr::filter(bar, if (TRUE) TRUE else TRUE)
#> Error in `collect()`:
#> ! Failed to collect lazy table.
#> Caused by error in `new_result()`:
#> ! nanodbc/nanodbc.cpp:1509: 00000: [RStudio][OracleOCI] (3000) Oracle Caller Interface: ORA-00920: invalid relational operator
```

Here's an example closer to my real use case for context :

```
fun <- function(lazy_tbl, type = c("a", "b")) {
  type <- match.arg(type)
  lazy_tbl %>%
    filter(
      # some filters that apply to "a" and "b"
     ...
      # conditional filter for "a" only
      if (type == "a") this_col > 0 else TRUE
    )
}
```

**Comment by mgirlich** [comment] 2023-04-24 13:38
The current translation seems to be

```sql
SELECT *
FROM (`df`)
WHERE (CASE WHEN TRUE THEN TRUE WHEN NOT TRUE THEN TRUE END)
```

@moodymudskipper can you provide a translation that works? And does the current translation work in `mutate()`? As I don't have an Oracle database to test with I need some help here.

**Comment by thomashulst** [comment] 2023-05-25 14:00
I just confirmed that the translation of `mutate()` also does not work on an Oracle backend, it results in the same error using the following translation:

```sql
SELECT 
CASE WHEN TRUE THEN TRUE WHEN NOT TRUE THEN TRUE END AS "x"
FROM (`df`)
```

I believe the issue with the current translation is that the CASE expression expects a condition (with an operator) to be evaluated and TRUE is not a valid type in Oracle. 

Not sure if this is the best way, but following translation of `filter()` would work:

```sql
SELECT * 
FROM (`df`)
WHERE 1 = CASE 
        WHEN 1=1 THEN 1
        WHEN NOT 1=1 THEN 1 END 
```

For `mutate()`:

```sql
SELECT CASE 
    WHEN 1=1 THEN 1
    WHEN NOT 1=1 THEN 1 END as "x"
FROM (`df`)
```

**Comment by mgirlich** [comment] 2023-05-26 11:31
@thomashulst @moodymudskipper Can one of you install the dev version (`remotes::install_github("tidyverse/dbplyr#1289")`) and give feedback whether a) the issue itself is fixed and b) no other issues occur due to the fix?

**Comment by thomashulst** [comment] 2023-05-26 12:29
```r
df <- tbl(con, in_schema("USER", "TEST")) |>
    filter(if(TRUE) TRUE else TRUE)
```
The above results in the following error on dev version:

```r
Error in db_query_fields.DBIConnection(con, ...) :
Caused by error:
! nanodbc/nanodbc.cpp:1752: HY000: [Oracle][ODBC][Ora]ORA-00933: SQL command not properly ended
```

with following SQL translation:

```sql
SELECT *
FROM "USER"."TEST" AS "q01"
WHERE (0 = 1)
```
I suspect the culprit is not actually this particular commit, as the following results in the same error:

```r
df <- tbl(con, in_schema("USER", "TEST"))
```

Table aliases in Oracle do not require the `AS` keyword: 

```sql
SELECT *
FROM "USER"."TEST" "q01"
WHERE (0 = 1)
```

should work.

**Comment by mgirlich** [comment] 2023-05-30 05:53
Thanks for the feedback. Quite surprising that `AS` is actually forbidden in Oracle... Then this will have to wait until another PR is merged.

**Comment by moodymudskipper** [comment] 2023-05-30 06:07
This might help:
https://stackoverflow.com/questions/8451195/is-the-as-keyword-required-in-oracle-to-define-an-alias

**Comment by mgirlich** [comment] 2023-06-13 09:43
The issue with the table alias is now fixed. Can you check again? :-)

**Comment by thomashulst** [comment] 2023-06-13 11:26
Almost :)

`mutate()`
```r
Error in collect(x, n = n) :
Caused by error:
! nanodbc/nanodbc.cpp:1752: HY000: [Oracle][ODBC][Ora]ORA-00905: missing keyword

<SQL> 'SELECT "TEST".*, CASE WHEN 1 = 1 THEN 1 = 1 WHEN NOT 1 = 1 THEN 1 = 1 END AS "x"
FROM "SCHEMA"."TEST"
FETCH FIRST 1000 ROWS ONLY'
```
`THEN` wants a result, i.e. `1` and not `1=1`. So following would work: 

<pre><sql>
SELECT "TEST".*, CASE WHEN 1 = 1 THEN <b>1</b> WHEN NOT 1 = 1 THEN <b>1</b> END AS "x"
FROM "SCHEMA"."TEST"
</pre>

Same goes for `filter()`, however, we also need to return the result of the `CASE` statement to the `WHERE` clause: 

<pre><sql>
SELECT "TEST".*
FROM "SCHEMA"."TEST"
WHERE <b>1 =</b> (CASE WHEN 1 = 1 THEN <b>1</b> WHEN NOT 1 = 1 THEN <b>1</b> END)
</pre>

(via: https://stackoverflow.com/a/44002586)

**Comment by moodymudskipper** [comment] 2023-06-13 12:54
This is what I have:

```

bar <- tbl(connect_to_db(), dbplyr::in_schema("DATA_MART", "D_PRODUKT_V"))
lazy <- dplyr::filter(bar, if (TRUE) TRUE else TRUE)
dplyr::show_query(lazy)
#> <SQL>
#> SELECT "D_PRODUKT_V".*
#> FROM "DATA_MART"."D_PRODUKT_V"
#> WHERE (CASE WHEN 1 = 1 THEN 1 = 1 WHEN NOT 1 = 1 THEN 1 = 1 END)
lazy
#> Error in `collect()`:
#> ! Failed to collect lazy table.
#> Caused by error in `new_result()`:
#> ! nanodbc/nanodbc.cpp:1509: 00000: [RStudio][OracleOCI] (3000) Oracle Caller Interface: ORA-00905: missing keyword

```

**Comment by mgirlich** [comment] 2023-06-14 07:22
Argh, this makes things way more complicated as `TRUE` and `FALSE` need different translations depending on whether they are used as a condition or as a value. This probably makes the handling more similar to MS SQL. I guess it would make more sense if someone who regularly uses OracleDB would tackle this.

**Comment by hadley** [comment] 2023-12-22 21:05
Looks like this might be fixed in Oracle 23c: https://oracle-base.com/articles/23c/boolean-data-type-23c. That was only released in September 2023, but it seems like any translation for older versions is going to be a significant amount of work. So maybe we can just document this as a limitation and offer a work around (i.e. use 0/1 instead of `FALSE`/`TRUE`)

**Closed** 2024-02-20 13:39 UTC
Labels: documentation
