### ISSUE TITLE
ODBC connection to Hive not usable due to prefixes in column names

### ISSUE THREAD

**Issue by pgramme** [tidyverse/dbplyr#573] opened 2021-01-07 16:09 UTC
Hi

I'm having troubles using `dbplyr` to extract and transform data from a Hive database. It seems due to dbplyr using aliased subqueries in the generated SQL, combined with the fact that the ODBC driver always outputs qualified column names (with table name as prefix).

Issue #315 was probably referring to the same problem.

Setup:

* Windows 10
* R package versions: dbplyr=2.0.0, dplyr=1.0.2, odbc=1.3.0, DBI=1.1.0
* [Cloudera's Hive ODBC driver](https://www.cloudera.com/downloads/connectors/hive/odbc/2-6-9.html)
* An ODBC connection properly setup to Hive on an external cluster

Here is a very simple minimal reprex, with comments.

``` r
library(DBI)
library(dplyr)
library(dbplyr)

# Connection 'My Hive cluster' was configured beforehand in Cloudera's ODBC driver for Hive
con <- dbConnect(odbc::odbc(), "My Hive cluster", timeout = 10, database = "my_db")

# Upload a very small table for our tests
TABLE_NAME <- "test_mpg"
dbWriteTable(con, TABLE_NAME, ggplot2::mpg %>% select(model:year) %>% head())

# Connect to that table and add a dummy column (within Hive):
mpg_db <- tbl(con, TABLE_NAME)
mpg_mod <- mpg_db %>% mutate(dummy = 1)

# Problem: the generated SQL includes unexpected column prefixes and crashes when executed:
show_query(mpg_mod)
#> <SQL>
#> SELECT `q01.model`, `q01.displ`, `q01.year`, 1.0 AS `dummy`
#> FROM `test_mpg`
mpg_mod %>% collect()
#> Error in new_result(connection@ptr, statement, immediate): nanodbc/nanodbc.cpp:1412: 42000: [Cloudera][Hardy] (80) Syntax or semantic analysis error thrown in server while executing query. Error message from server: Error while compiling statement: FAILED: SemanticException [Error 10004]: Line 1:7 Invalid table alias or column reference 'q01.model': (possible column names are: model, displ, year)

# Note that initial colnames are prefixed with 'q01.' in op_vars(), and with Hive table name in
# collect(). The new column has no prefix in op_vars()
print(list(
  init_opvars = mpg_db %>% op_vars(),
  init_collect = mpg_db %>% collect() %>% colnames(),
  mod_opvars = mpg_mod %>% op_vars()
))
#> $init_opvars
#> [1] "q01.model" "q01.displ" "q01.year" 
#> 
#> $init_collect
#> [1] "test_mpg.model" "test_mpg.displ" "test_mpg.year" 
#> 
#> $mod_opvars
#> [1] "q01.model" "q01.displ" "q01.year"  "dummy"

# Clean up
dbRemoveTable(con, TABLE_NAME)
dbDisconnect(con)
```

<sup>Created on 2021-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I was able to find a hack-fix by manually removing the prefix in the `tbl_sql` object:

``` r
# Hack: remove prefix in table def (NB: see code above for its definition)
mpg_db[["ops"]]$vars <- sub("^q\\d\\d\\.","", mpg_db[["ops"]]$vars)
# Now the two following expressions work
mpg_mod <- mpg_db %>% mutate(dummy = 1)
mpg_mod2 <- mpg_mod %>% mutate(other = 2) %>% filter(other == 2)

# Note that initial colnames are prefixed with 'q01.' in op_vars(), and with Hive table name in
# collect(). The new column has no prefix in op_vars()
print(list(
  init_opvars = mpg_db %>% op_vars(),
  init_collect = mpg_db %>% collect() %>% colnames(),
  mod_opvars = mpg_mod %>% op_vars(),
  mod_collect = mpg_mod %>% collect() %>% colnames(),
  mod2_opvars = mpg_mod2 %>% op_vars(),
  mod2_collect = mpg_mod2 %>% collect() %>% colnames()
))
#> $init_opvars
#> [1] "model" "displ" "year" 
#> 
#> $init_collect
#> [1] "test_mpg.model" "test_mpg.displ" "test_mpg.year" 
#> 
#> $mod_opvars
#> [1] "model" "displ" "year"  "dummy"
#> 
#> $mod_collect
#> [1] "test_mpg.model" "test_mpg.displ" "test_mpg.year"  "dummy"         
#> 
#> $mod2_opvars
#> [1] "model" "displ" "year"  "dummy" "other"
#> 
#> $mod2_collect
#> [1] "q02.model" "q02.displ" "q02.year"  "q02.dummy" "q02.other"
```

It works, but the `q02.` prefix in the final output will seem strange to a user who doesn't know the internals of dbplyr.

The bug is probably due differences between:
  * `sql_query_fields.DBIConnection(...)` which uses an auto-named sql_subquery
  * `sql_render.op_select(...)` which doesn't use any subquery when `op$x` is an `op_base_remote`

And it wouldn't be a problem if the ODBC driver didn't always output qualified column names.

I'm not sure what is the right way to fix it, though... Willing to help if I can!

Thanks
Pierre

**Comment by pgramme** [comment] 2021-01-20 13:35
Hi!

Has anyone been able to reproduce this with the provided reprex? Does it also affect non-Windows versions of the ODBC driver?

Can you maybe think of a workaround so that Hive connections are still usable with dbplyr?

Thanks
Pierre

**Comment by hadley** [comment] 2021-01-21 15:06
@pgramme unfortunately it's hard for me to help because I don't access to a hive database. But it seems like the problem might be happening early on when dbplyr gets the column names from the table. Can you please try running this code? (you might need to tweak it a bit to get it to work, since I can't run it myself):

```R
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)

con <- DBI::dbConnect(odbc::odbc(), "My Hive cluster", timeout = 10, database = "my_db")
DBI::dbWriteTable(con, "test", data.frame(x = 1:10, y = 1:10))

db <- tbl(con, "test")
tbl_vars(db)

db_query_fields(con, "test")
```

Assuming the problem is that the table prefix is automatically added when it should be, it remains to figure out why this is happening. [This thread](https://community.cloudera.com/t5/Support-Questions/Remove-qualifier-from-column-name/td-p/213864) suggests that it might be the driver, and you might be able to work around it by setting [`hive.resultset.use.unique.column.names`](https://stackoverflow.com/questions/31705985/is-it-possible-to-stop-hive-from-printing-the-database-when-printing-column-head) to false.

If you can't set it globally, it [looks like you](https://support.aginity.com/hc/en-us/community/posts/360029546173-Column-headers-in-Hive) you might be able to set for a given connection:

```R
DBI::dbExecute(con, "set hive.resultset.use.unique.column.names=false;")
```

**Comment by pgramme** [comment] 2021-01-22 18:17
@hadley Thanks for having a look, and for your pointer to the Hive setting: this can be adapted to a solution in most cases (but still has a few problems, see below).

I had to adapt your last line a bit to make your test run:

    # [omitted: setup as you wrote]
    tbl_vars(db)
    #> <dplyr:::vars>
    #> [1] "q01.x" "q01.y"
    
    db_query_fields(con, ident("test"))
    #> [1] "q02.x" "q02.y"
    
    colnames(db %>% collect())
    #> [1] "test.x" "test.y"

The explanation for the 'q0x' prefix lies in the SQL query used underneath `tbl(con, "test")` and `db_query_fields(...)`:

    sql_query_fields(con, ident("test"))
    #> <SQL> SELECT *
    #> FROM `test` AS `q01`
    #> WHERE (0 = 1)

----

For the fix, I don't want to set `hive.resultset.use.unique.column.names=false` globally for the whole Hive server since it might break production jobs. I tried to run it from my DBI connection, but it is ignored as shown here:

    # Unsuccessful:
    DBI::dbExecute(con, "set hive.resultset.use.unique.column.names=false;")
    db_query_fields(con, ident("test"))
    #> [1] "q07.x" "q07.y"

    # Unsuccessful:
    colnames(dbGetQuery(con, "set hive.resultset.use.unique.column.names=false; SELECT * FROM test"))
    #> data frame with 0 columns and 0 rows

I finally managed to specify that setting in the ODBC driver options (for the record: under Advanced Options > Server Side Properties), and the prefix problem is then solved. The generated SQL is still the same (of course) but the test gives the expected results with exactly the same code:

    # [omitted: setup as you wrote]
    tbl_vars(db)
    #> <dplyr:::vars>
    #> [1] "x" "y"
    db_query_fields(con, ident("test"))
    #> [1] "x" "y"

So thanks a lot for the idea!

----

Note however that this setting is problematic in self-joins, when prefix is required on some column names to make them unique:

    dbjoin <- tbl(con, sql("select * from test t1 join test t2 on t1.x=t2.x"))
    dbjoin %>% collect() %>% colnames()
    #> Error: Column names `x` and `y` must not be duplicated.

    # NB: before changing the setting, this ran without error, giving: [1] "t1.x" "t1.y" "t2.x" "t2.y"

----

**Interesting point:** even without modifying the Hive setting, the Connection pane in RStudio is able to show column names _without prefix_. If I understand correctly, that's because it is based on `odbc::odbcListColumns()` and `odbc::odbcConnectionColumns()` which never include the prefix. In the DBI package, `DBI::dbListFields()` also never includes the prefix. 

Could these be used inside `db_query_fields()` for a solution which works whatever the driver settings and also allows for self-joins?

Pierre

**Comment by hadley** [comment] 2021-01-22 19:32
Hmmmm, that's an interesting idea. `db_query_fields()` also has to be able to find the fields associated with an arbitrary SQL query, but that's relatively uncommon, so making it use `dbListFields()` conditionally for tables would be useful.

What does `tbl_vars(dbjoin)` return?

**Comment by hadley** [comment] 2021-01-22 19:33
And could you please give me a traceback for the `dbjoin %>% collect()` call?

**Comment by hadley** [comment] 2021-01-22 22:13
Also looks like you can set the properties when you make a connection: https://community.rstudio.com/t/send-hiveconfs-with-odbc-hive-query/63433/4?u=hadley

**Comment by pgramme** [comment] 2021-01-25 11:20
Indeed, I was able to set the server-side property while making the connection. Same synthax for my Cloudera's Hive ODBC driver as with Simba's in your linked post:

    con <- DBI::dbConnect(
      odbc::odbc(), dsn = "My Hive cluster", timeout = 10, 
      SSP_hive.resultset.use.unique.column.names=TRUE)  # NB: ...="true" also works

Here is the additional info you asked:

    > tbl_vars(dbjoin)
    <dplyr:::vars>
    [1] "x" "y" "x" "y"

    > dbjoin %>% collect() %>% colnames()
    Error: Column names `x` and `y` must not be duplicated.
    Run `rlang::last_error()` to see where the error occurred.
    > rlang::last_trace()
    x
    +-<error/tibble_error_column_names_must_be_unique>
    | Column names `x` and `y` must not be duplicated.
    \-<error/vctrs_error_names_must_be_unique>
      Names must be unique.
    Backtrace:
         x
      1. +-dbjoin %>% collect() %>% colnames()
      2. +-base::colnames(.)
      3. | \-base::is.data.frame(x)
      4. +-dplyr::collect(.)
      5. \-dbplyr:::collect.tbl_sql(.)
      6.   \-dplyr::grouped_df(out, intersect(op_grps(x), names(out)))
      7.     +-tibble::as_tibble(data)
      8.     \-tibble:::as_tibble.data.frame(data)
      9.       \-tibble:::lst_to_tibble(unclass(x), .rows, .name_repair)
     10.         \-tibble:::set_repaired_names(x, .name_repair)
     11.           +-rlang::set_names(...)
     12.           \-tibble:::repaired_names(...)
     13.             +-tibble:::subclass_name_repair_errors(...)
     14.             | \-base::withCallingHandlers(...)
     15.             \-vctrs::vec_as_names(...)
     16.               \-(function () ...
     17.                 \-vctrs:::validate_unique(names = names, arg = arg)
     18.                   \-vctrs:::stop_names_must_be_unique(names, arg)
     19.                     \-vctrs:::stop_names(...)
     20.                       \-vctrs:::stop_vctrs(class = c(class, "vctrs_error_names"), ...)


When using `DBI::dbGetQuery()` directly (which is similar to the intermediate step done within `db_collect.DBIConnection()`), I get a data.frame with duplicated column names. To avoid the error when making the tibble from that data frame, dbplyr could use `tibble(out, .name_repair = "minimal")` but anyway the result wouldn't be usable in any dplyr function.

**Comment by pgramme** [comment] 2021-01-25 11:55
For info, I just tried the same self-join on a SQLite connection: `DBI::dbGetQuery()` gives the same output (with duplicated column names), `tbl_vars()` resolves the duplicates, but `collect()` fails with the same error (and same stack trace). See below:

    > q <- "select * from test_r t1 join test_r t2 on t1.x=t2.x"
    > DBI::dbGetQuery(con, q)
      x y x y
    1 1 1 1 1
    2 2 2 2 2
    ...
    
    > dbjoin <- tbl(con, sql(q))
    > tbl_vars(dbjoin)
    <dplyr:::vars>
    [1] "x"   "y"   "x:1" "y:1"

    > dbjoin %>% collect() %>% colnames()
    Error: Column names `x` and `y` must not be duplicated.

One more thing: instead of writing the self-join SQL myself as I did, I can use `dplyr::inner_join(db, db, by = "x")` to build the SQL. Then suffixes are added where needed to make the names unique. This is valid both for SQLite and for Hive. That's an easy workaround the whole self-join problem...

**Comment by hadley** [comment] 2021-01-25 12:59
So at a minimum I think `collect()` needs to take a `.name_repair` argument so that it can be passed on if need, but otherwise it sounds like most of the fix is in the `use.unique.column.names` parameter? 

I wonder where the best place to document the setting is. Maybe https://db.rstudio.com/databases/hive/ ?

**Comment by pgramme** [comment] 2021-01-25 13:14
+1 for the `.name_repair` argument to collect().

And OK too with your conclusion that `use.unique.column.names` is the key here. The URL you suggest seems fine. If you want, I can also open a new question and answer it myself in Community/Stackoverflow, just to help others find the info.

Is it also feasible to try and detect the absence of the setting? E.g. in `sql_query_fields.DBIConnection()`, then have a tip message linking to the doc? Or do you think it would be too heavy?

**Comment by hadley** [comment] 2021-01-25 15:40
If you can show me the code to determine if it's set for a connection, I can figure out where to provide a warning in dbplyr.

**Comment by blairj09** [comment] 2021-01-28 20:19
I've added some context on this issue to db.rstudio.com: https://github.com/rstudio/db.rstudio.com/pull/115

**Comment by hadley** [comment] 2021-02-02 22:56
This seems like as much as we can do for now. Thanks everyone!

**Closed by hadley** 2021-02-02 22:56 UTC
Labels: backend :man_dancing:, bug
