### ISSUE TITLE
copy_to or db_copy_to not working

### ISSUE THREAD

**Issue by fahadshery** [tidyverse/dbplyr#346] opened 2019-08-12 11:46 UTC
Creating a pool:

```r
con<- pool::dbPool(odbc::odbc(), dsn = "my_DSN",
                  PWD    = rstudioapi::askForPassword("Database password"))
```

```{r}
db_desc(con)

[1] "Oracle 12.01.0020[user@remote_db/]"
```

Here is the error:
```r
copy_to(con, mtcars, "mtcars", temporary = FALSE)

Error in connection_sql_tables(conn@ptr, catalog_name = if ("catalog" %in% : nanodbc/nanodbc.cpp:4266: HYC00: [Oracle][ODBC]Optional feature not implemented.
```

Also tried:
```r
db_copy_to(con, mtcars, "mtcars", temporary = FALSE)

Error in UseMethod("as.sql") : no applicable method for 'as.sql' applied to an object of class "data.frame"
```

session info:

```r
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] janitor_1.1.1          pool_0.1.4.2           dbplyr_1.4.2           DBI_1.0.0              data.table_1.11.8      qdap_2.3.0            
 [7] RColorBrewer_1.1-2     qdapTools_1.3.3        qdapRegex_0.7.2        qdapDictionaries_1.0.7 textclean_0.9.3        drlib_0.1.0           
[13] lubridate_1.7.4        ggrepel_0.8.0          fpp2_2.3               expsmooth_2.3          fma_2.3                forecast_8.5          
[19] recipes_0.1.5          textSummary_0.1.0      scales_1.0.0           forcats_0.3.0          stringr_1.4.0          dplyr_0.8.1           
[25] purrr_0.2.5            readr_1.2.1            tidyr_0.8.2            tibble_2.1.1           ggplot2_3.2.0          tidyverse_1.2.1       

loaded via a namespace (and not attached):
 [1] openNLPdata_1.5.3-4 colorspace_1.4-1    class_7.3-14        rprojroot_1.3-2     snakecase_0.9.2     base64enc_0.1-3    
 [7] rstudioapi_0.8      bit64_0.9-7         fansi_0.4.0         prodlim_2018.04.18  xml2_1.2.0          splines_3.5.0      
[13] knitr_1.20          jsonlite_1.6        venneuler_1.1-0     rJava_0.9-10        broom_0.5.1         compiler_3.5.0     
[19] httr_1.3.1          backports_1.1.2     assertthat_0.2.1    Matrix_1.2-14       lazyeval_0.2.2      cli_1.1.0          
[25] later_0.8.0         htmltools_0.3.6     tools_3.5.0         igraph_1.2.2        NLP_0.2-0           gtable_0.3.0       
[31] glue_1.3.1          reshape2_1.4.3      Rcpp_1.0.1          slam_0.1-43         cellranger_1.1.0    fracdiff_1.4-2     
[37] urca_1.3-0          gdata_2.18.0        nlme_3.1-137        lmtest_0.9-36       timeDate_3043.102   gower_0.1.2        
[43] gender_0.5.2        xlsxjars_0.6.1      rvest_0.3.2         gtools_3.8.1        xlsx_0.6.1          XML_3.98-1.16      
[49] MASS_7.3-49         zoo_1.8-5           odbc_1.1.6          ipred_0.9-8         hms_0.4.2           parallel_3.5.0     
[55] yaml_2.2.0          quantmod_0.4-14     curl_3.3            gridExtra_2.3       rpart_4.1-13        stringi_1.4.3      
[61] tseries_0.10-46     plotrix_3.7-4       TTR_0.23-4          openNLP_0.2-6       lava_1.6.4          chron_2.3-53       
[67] rlang_0.4.0         pkgconfig_2.0.2     bitops_1.0-6        evaluate_0.12       lattice_0.20-35     bit_1.1-14         
[73] tidyselect_0.2.5    plyr_1.8.4          magrittr_1.5        R6_2.4.0            generics_0.0.2      pillar_1.3.1       
[79] haven_2.0.0         withr_2.1.2         xts_0.11-2          survival_2.41-3     RCurl_1.95-4.11     nnet_7.3-12        
[85] modelr_0.1.2        crayon_1.3.4        utf8_1.1.4          wordcloud_2.6       rmarkdown_1.10      grid_3.5.0         
[91] readxl_1.1.0        blob_1.1.1          reports_0.1.4       digest_0.6.18       tm_0.7-5            munsell_0.5.0      
[97] quadprog_1.5-5     

```

**Comment by hadley** [comment] 2019-12-13 19:56
Can you please provide a minimal reproducible example using the [reprex](http://reprex.tidyverse.org) package? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it. If you've never made a minimal reprex before, there is lots of good advice [here](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html).

**Comment by hadley** [comment] 2020-04-14 22:05
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2020-04-14 22:05 UTC
Labels: reprex
