### ISSUE TITLE
Error when collecting after using reduce and union_all with dbplyr 2.2.0 and Oracle

### ISSUE THREAD

**Issue by Janlow** [tidyverse/dbplyr#914] opened 2022-06-16 08:44 UTC
Hi! After updating to dbplyr 2.2.0 I found an error when using union_all and reduce to bind multiple Oracle dataframes together. The error only occurs when collecting. I am getting ORA error 24374 which seems to indicate something with commenting on multiple lines. I will give you a very easy example of the problem and the difference between dbplyr 2.1.0 and 2.2.0. 

```r
library(dplyr)
library(dbplyr) # version 2.1.0

# df is an oracle table similar to lazy_frame(ID = c(1001, 1002, 1003, 1004), NAME= c("x", "y", "z", "w"), con = simulate_oracle())

df
# Source:   table<"TABLE"."NAME"> [?? x 2]
# Database: Oracle 
     ID NAME  
  <dbl> <chr>         
1  1001 x   
2  1002 y
3  1003 z
4  1004 w

temp_list <- list()

temp_list[[1]] <- df
temp_list[[2]] <- df
temp_list[[3]] <- df

final <- purrr::reduce(temp_list, union_all)

final 
# Source:   lazy query [?? x 2]
# Database: Oracle
      ID NAME
   <dbl> <chr>         
 1  1001 x   
 2  1002 y    
 3  1003 z
 4  1004 w
 5  1001 x   
 6  1002 y
 7  1003 z
 8  1004 w
 9  1001 x   
10  1002 y
# ... with more rows

final %>% collect()
# A tibble: 12 x 2
      ID NAME
   <dbl> <chr>         
 1  1001 x
 2  1002 y
 3  1003 z
 4  1004 w
 5  1001 x
 6  1002 y
 7  1003 z
 8  1004 w
 9  1001 x   
10  1002 y
11  1003 z
12  1004 w
```

When using dbplyr 2.2.0 I am getting the Ora error mentioned above when collecting. 

```r
library(dplyr)
library(dbplyr) # version 2.2.0

# df is an oracle table similar to lazy_frame(ID = c(1001, 1002, 1003, 1004), NAME= c("x", "y", "z", "w"), con = simulate_oracle())

df
# Source:   table<"TABLE"."NAME"> [4 x 2]
# Database: Oracle 
     ID NAME  
  <dbl> <chr>         
1  1001 x   
2  1002 y
3  1003 z
4  1004 w

temp_list <- list()

temp_list[[1]] <- df
temp_list[[2]] <- df
temp_list[[3]] <- df

final <- purrr::reduce(temp_list, union_all)

final 
# Source:   SQL [?? x 2]
# Database: Oracle
      ID NAME
   <dbl> <chr>         
 1  1001 x   
 2  1002 y    
 3  1003 z
 4  1004 w
 5  1001 x   
 6  1002 y
 7  1003 z
 8  1004 w
 9  1001 x   
10  1002 y
# ... with more rows

final %>% collect()
Error: nanodbc/nanodbc.cpp:1655: HY000: [Oracle][ODBC][Ora]ORA-24374: define not done before fetch or execute and fetch
 
<SQL> '(
  (
    SELECT *
    FROM "TABLE"."NAME"
  )
  UNION ALL
  (
    SELECT *
    FROM "TABLE"."NAME"
  )
)
UNION ALL
(
  SELECT *
  FROM "TABLE"."NAME"
)'
```

**Comment by mgirlich** [comment] 2022-06-17 04:45
Closing this because it is a duplicate of #908.

**Closed by mgirlich** 2022-06-17 04:45 UTC
