### ISSUE TITLE
dbplyr 1.4.0 breaks filters with subsetted variables using SQLite

### ISSUE THREAD

**Issue by rundel** [tidyverse/dbplyr#289] opened 2019-04-29 02:10 UTC
The last two filters below fail, the first returns no results and the second throws `Error in result_create(conn@ptr, statement) : near "AS": syntax error`. I had similar code to this in a production shiny app that was working under the previous version and broke once we upgrade to dbplyr 1.4.0.

```r
library(dplyr)

test = DBI::dbConnect(RSQLite::SQLite(), ":memory:")
copy_to(test, iris)

iris_db = tbl(test, "iris")

key_vec = c(species = "setosa")
key_list = list(species = "setosa")

filter(iris_db, Species == key_vec)
filter(iris_db, Species == key_vec["species"])
filter(iris_db, Species == key_list["species"])
```

**Comment by hadley** [comment] 2019-04-29 15:37
I think this is a duplicate of #269, so until it's fixed, you can work around it by stripping variable names (or using `[[`).

**Closed by hadley** 2019-04-29 15:37 UTC

**Comment by rundel** [comment] 2019-04-29 15:49
It seems like it is related to #269 but I think something bigger is going on. The issue isn't about the vector or list being named since `filter(iris_db, Species == key_vec)` from the original reprex works correctly.

Also, using `[[` also do not resolve the issue, it produces the same error but due to different faulty SQL.

```r
filter(iris_db, Species == key_list["species"])
#> Error in result_create(conn@ptr, statement): near "AS": syntax error

filter(iris_db, Species == key_list["species"]) %>% show_query()
#> <SQL>
#> SELECT *
#> FROM `iris`
#> WHERE (`Species` = CASE WHEN ('species') THEN (('setosa' AS `species`)) END)

filter(iris_db, Species == key_list[["species"]])
#> Error in result_create(conn@ptr, statement): near "AS": syntax error

filter(iris_db, Species == key_list[["species"]]) %>% show_query()
#> <SQL>
#> SELECT *
#> FROM `iris`
#> WHERE (`Species` = ('setosa' AS `species`).`species`)
```

**Comment by hadley** [comment] 2019-04-29 20:07
That's also because of the breaking change: `[[` is no longer evaluated locally.
