### ISSUE TITLE
Stacking another arrange does not clear previous arrange

### ISSUE THREAD

**Issue by alexfun** [tidyverse/dbplyr#348] opened 2019-08-15 06:41 UTC
While investigating https://github.com/tidyverse/dbplyr/issues/345 I have found something similar happening when trying to override a previous ordering. First, set up the same data:

```
tmp_cars_sdf <-
    copy_to(con_psql, cars, name = "tmp_cars_sdf", overwrite = T)
```

Then do the following (compute lagged differences by group, first sorting in ascending order, then descending order):

```
tmp_out <-
    tmp_cars_sdf %>%
    arrange(speed, dist) %>%
    mutate(diff_dist_up = dist - lag(dist)) %>%
    arrange(speed, desc(dist)) %>%
    mutate(diff_dist_down = dist - lag(dist)) 
```
Running `remote_query(tmp_out)` shows that something is wrong (emphasis mine):

> <SQL> SELECT "speed", "dist", "diff_dist_up", "dist" - LAG("dist", 1, NULL) OVER (**ORDER BY "speed", "dist", "speed", "dist" DESC**) AS "diff_dist_down"
> FROM (SELECT *
> FROM (SELECT "speed", "dist", "dist" - LAG("dist", 1, NULL) OVER (ORDER BY "speed", "dist") AS "diff_dist_up"
> FROM (SELECT *
> FROM "tmp_cars_sdf"
> ORDER BY "speed", "dist") "dbplyr_061") "dbplyr_062"
> ORDER BY "speed", "dist" DESC) "dbplyr_063"

**Comment by alexfun** [comment] 2019-08-16 01:19
I am on dbplyr 1.4.2

**Comment by krlmlr** [comment] 2019-09-05 16:30
Would that be covered by #276?

**Comment by alexfun** [comment] 2019-09-25 03:33
Unfortunately I do not really understand #276 to make a sensible reply to your question, but I don't understand why the second `arrange` can't override the first `arrange` and result in:


> SELECT "speed", "dist", "diff_dist_up", "dist" - LAG("dist", 1, NULL) OVER (ORDER BY "speed", "dist" DESC) AS "diff_dist_down"
> FROM (SELECT *
> ...
> 

I have taken to using the `unarrange` function from https://stackoverflow.com/a/57505930/ as a work-around to this:

```
    tmp_cars_sdf %>%
    arrange(speed, dist) %>%
    mutate(diff_dist_up = dist - lag(dist)) %>%
    unarrange() %>%
    arrange(speed, desc(dist)) %>%
    mutate(diff_dist_down = dist - lag(dist)) 
```

**Comment by hadley** [comment] 2019-12-13 19:54
Can you please provide a minimal reproducible example using the [reprex](http://reprex.tidyverse.org) package? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it. If you've never made a minimal reprex before, there is lots of good advice [here](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html).

**Comment by hadley** [comment] 2020-04-14 22:05
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2020-04-14 22:05 UTC
Labels: reprex
