### ISSUE TITLE
Ability to reference different databases

### ISSUE THREAD

**Issue by aris-hastings** [tidyverse/dbplyr#653] opened 2021-05-11 15:20 UTC
Hi Everyone, 

In_schema() functionality is great for working across tables across multiple schemas; however, more often then not data is spread across multiple databases. Would it be possible to extend in_schema to allow reference at a database level? or perhaps a dedicated in_database() function which can be used when this level of functionality is required?

Many thanks,
Aris

**Comment by mgirlich** [comment] 2022-04-06 13:09
Which databases support to query data from different databases? And how does the syntax look like?
@aris-hastings Can you help here?

**Comment by hadley** [comment] 2022-04-10 12:47
Duplicate of #806

**Closed by hadley** 2022-04-10 12:47 UTC
Labels: feature
